
'''
This replace:
: \"([-+0-9A-Za-z \(\),\/.]*)\",
: (pooled, 100, pooled, pooled, ''),
'''

pooled = 'Pooled cell/tissue RNA-seq'
single_cell = 'Single cell RNA-seq'

cell_source = {
    "eos im lm": pooled,
    "eos im lp": pooled,
    "mac im lm": pooled,
    "mac im lp": pooled,
    "mac ip lm": pooled,
    "mac ip lp": pooled,
    "adipocytes": pooled,
    "adipocytes brown": pooled,
    "adipose": pooled,
    "BM": pooled,
    "BMDM": pooled,
    "BMDM cpg": pooled,
    "BMDM IL1b": pooled,
    "BMDM MALP2": pooled,
    "BMDM pIFNg": pooled,
    "BMDM pIL4": pooled,
    "BMDM pINFa": pooled,
    "BMDM TGFb": pooled,
    'DP': pooled,
    "DN1": pooled,
    "DN2a": pooled,
    "DN2b": pooled,
    "DN3": pooled,
    "CD4T Treg": pooled,
    "CD4T iTreg": pooled,
    "CD4T mIL21": pooled,
    "CD4T pIL21": pooled,
    "CD4T Th17": pooled,
    "CD4T Th1": pooled,
    "CD4T Th2": pooled,
    "CD4T Th9": pooled,
    "CD4Tcd328": pooled,
    "CD4Tuntre": pooled,
    "CD8T untre": pooled,
    "CD8T il2": pooled,
    "CD4T naive acd328": pooled,
    "cerebellum": pooled,
    "cortex": pooled,
    "dendritic cells": pooled,
    "E105 forelimb": pooled,
    "E105 hindlimb": pooled,
    "E16dermis": pooled,
    "E16epidermis": pooled,
    "E16skin": pooled,
    "ESC": pooled,
    "ESC V65": pooled,
    "ESC ZHBTc4": pooled,
    "heart": pooled,
    "intestine": pooled,
    "kidney": pooled,
    "liver": pooled,
    "lung": pooled,
    "lungFibroblasts": pooled,
    "MEF": pooled,
    "Neuron NCAMp": pooled,
    "NPC": pooled,
    "preadipocytes": pooled,
    "preadipocytes brown": pooled,
    "preB": pooled,
    "primary adipocytes brown": pooled,
    "primary adipocytes white": pooled,
    "proB": pooled,
    "spinalcord": pooled,
    "spleen": pooled,
    "TSC": pooled,
    "BcellCD43m": pooled,
    "BcellsCD19p": pooled,
    "cerebrum": pooled,
    "fatpad": pooled,
    "GenitalFatPad": pooled,
    "LgIntestine": pooled,
    "liver E1429bkgd": pooled,
    "liverE145": pooled,
    "naiveT": pooled,
    "thymus": pooled,
    "WholeBrainE14": pooled,
    "WholeBrainE18": pooled,
    "mst im lm": pooled,
    "mst im lp": pooled,
    "mst ip lm": pooled,
    "mst ip lp": pooled,
    "neu im lm": pooled,
    "neu im lp": pooled,
    "neu ip lm": pooled,
    "neu ip lp": pooled,
    "sdc im lm": pooled,
    "sdc im lp": pooled,
    "sdc ip lm": pooled,
    "sdc ip lp": pooled,  
    "DC CD11bp": pooled,
    "DC CD8p": pooled,
    "testicular": pooled,
    "BMDM lipidA 0m": pooled,
    "BMDM lipidA 360m": pooled,
    "E165 cortical neurons": pooled,
    "elongative spermatids": pooled,
    "erythroblast": pooled,
    "leptotene spermatocytes": pooled,
    "megakaryoblast": pooled,
    "megakryocyte erythroid progenitor": pooled,
    "pachytene spermatocytes": pooled,
    "pgc": pooled,
    "prim typeA spermatogonia": pooled,
    "proB fracB": pooled,
    "proB fracCC": pooled,
    "round spermatids": pooled,
    "splenicB cells": pooled,
    "striatal neurons": pooled,
    "typeA spermatogonia": pooled,
    "typeB spermatogonia": pooled,
    "brain": pooled, 
    "cerebellar gran neurons": pooled,
    "colon": pooled,
    "dorsal rootganglia": pooled,
    "epidermis basal E14": pooled,
    "epidermis suprabasal E14": pooled,
    "ESC B6J": pooled,
    "eye": pooled,
    "hair follicle": pooled,
    "keratinocytes": pooled,
    "lower molar": pooled,
    "motor neurons": pooled,
    "myoblast": pooled,
    "neocortex cortical plate": pooled,
    'neocortex subventricular zone': pooled,
    'neocortex ventricular zone': pooled,
    'oocytes': pooled,
    'pineal gland': pooled,
    'placenta': pooled,
    'retina': pooled,
    'skeletal muscle': pooled,
    'sperm': pooled,
    'striated muscle': pooled,
    'substantia nigra': pooled,
    'telencephalon': pooled,
    'upper molar': pooled,
    'ventral tagmental': pooled,
    "blastocyst": pooled,
    "ICM E375": pooled,
    "ICM E35": pooled,
    "Epiblast": pooled,
    "trophoblast giant cells": pooled,
    "patski": pooled,
    "dentate gyrus": pooled,
    'B germinal center': pooled,
    'B resting': pooled,
    'Bactive': pooled,
    'Bnaive': pooled,
    "Caecum": pooled,
    'cardiac precursors': pooled,
    'cardiomyocytes': pooled,
    'cortical thymic epithelial': pooled,
    'medullary thymic epithelial': pooled,
    'dermal fibroblast': pooled,
    'epididymis': pooled,
    'EpiSC': pooled,
    'erythroid progenitor': pooled,
    'frontal cortex': pooled,
    'granulocytes': pooled,
    'Intestinal subepithelial myofibroblasts adult': pooled,
    'Intestinal subepithelial myofibroblasts neonatal': pooled,
    'mesodermal cells': pooled,
    'myelocytes': pooled,
    'promyelocytes': pooled,
    'neonatal tail fibroblast': pooled,
    'olfactory bulb': pooled,
    'oviduct': pooled,
    'uterus': pooled,
    'vas deferens': pooled,
    'X2C embryo': pooled,
    'X4C embryo': pooled,
    'X8C embryo': pooled,
    'prostate basal cells': pooled,
    'skin epithelial': pooled,
    'striatum': pooled,
    'subventricularzone': pooled,
    'tail fibroblast': pooled,
    'HSC': pooled,
    'myeloid': pooled,
    'nucleus accumbens': pooled,
    'morula': pooled,
    "Embryo2C early E1 C2": single_cell, # The single cell embryo data.
    'Embryo2C late E6 C2': single_cell,
    'Embryo2C mid E5 C2': single_cell,
    'Early blastocyst E4 C8': single_cell, 
    'Early blastocyst E2 C16': single_cell,
    'Late blastocyst E2 C2': single_cell, # I can't identify a good ICM sample, so rely on other data for ICM
    'Late blastocyst E2 C8': single_cell,
    'Mid blastocyst E2 C17': single_cell,
    'Mid blastocyst E2 C9': single_cell,
    'Embryo4C E1 C2': single_cell,
    'Embryo8C E1 C1': single_cell,
    'Morula E1 C10': single_cell,
    'basophilic erythroblast': pooled,
    'BM monocyte': pooled,
    'cortex neuron': pooled,
    'hippocampus neuron': pooled,
    'hippocampus': pooled,
    'hippocampus tissue': pooled,
    'ileum': pooled,
    'mammary tissue': pooled,
    'Matrue sperm': pooled,
    'microglia': pooled,
    'orthochromatic erythroblast': pooled,
    'polychromatic erythroblast': pooled,
    'proerythroblast': pooled,
    'pronuclei': pooled,
    'Spermatids': pooled,
    'Spermatocytes': pooled,
    'Spermatogonia': pooled,
    'white matter glia': pooled,
    'TER119p erythroid cells': pooled,
    'Zygote E1 C1': single_cell,
    'E105 central neural epithelium': pooled,
    'E105 dorsal control neural epithelium': pooled,
    'E105 lateral prominence neural epithelium': pooled,
    'E105 mandibular arch': pooled,
    'E105 maxillary arch': pooled,
    'E105 medial nasal prominence': pooled,
    'E85 caudal brain neural epithelium': pooled,
    'E85 non floor plate neural epithelium': pooled,
    'E95 cranial mesenchyme': pooled,
    'E95 epidermal ectoderm': pooled,
    'E95 mandibular arch': pooled,
    'E95 maxillary arch': pooled,
    'ILC2': pooled,
    'ESC 2iL HVn': pooled,
    'ESC 2iL HVp': pooled,
    'adipocytes white': pooled,
    'adrenal medulla': pooled,
    'astrocyte': pooled,
    'B active': pooled,
    'B cells CD19p': pooled,
    'B cells CD43m': pooled,
    'B naive': pooled ,
    'BM macrophages': pooled,
    'caecum': pooled,
    'carotid body': pooled,
    'CD4T cells': pooled,
    'CD4T DPCD3hi': pooled,
    'CD4T DPCD3lo': pooled,
    'CD8T': pooled,
    'CD8T nkg2dn': pooled,
    'CD8T nkg2dp': pooled,
    'cerebral cortex endothelium': pooled,
    'chondrocyte rib': pooled,
    'CLP': pooled,
    'CMP': pooled,
    'colon epithelial cells': pooled,
    'cranial neural crest mandible': pooled,
    'DN1eP': pooled,
    'DN1ePNKT': pooled,
    'E105 lateral nasal prominence': pooled,
    'E105 olfactory pit': pooled,
    'E125 atrioventricular canal': pooled,
    'E165 skin': pooled,
    'E185 dermis': pooled,
    'E185 epidermis': pooled,
    'E65 Epiblast AD': pooled,
    'E65 Epiblast AP': pooled,
    'E65 Epiblast PD': pooled,
    'E65 Epiblast PP': pooled,
    'E85 floor plate': pooled,
    'E85 mesoderm': pooled,
    'ectoplacental cone': pooled,
    'erythrocytes typeA': pooled,
    'erythrocytes typeB': pooled,
    'ESC groundstate line1': pooled,
    'ESC naive 2iL': pooled,
    'ESC naive 2iLGO': pooled,
    'ESC PDL': pooled,
    'GMP': pooled,
    'hair follicle stem cells': pooled,
    'hair follicle transit amplifying cells': pooled,
    'HSC MPP1': pooled,
    'HSC MPP2': pooled,
    'HSC MPP3': pooled,
    'HSC MPP4': pooled,
    'iNKT': pooled,
    'intestinal stem cell': pooled,
    'intestinal subepithelial myofibroblasts adult': pooled,
    'intestinal subepithelial myofibroblasts neonatal': pooled,
    'large intestine': pooled,
    'LTHSC': pooled,
    'mast cells cd25n': pooled,
    'mast cells cd25p': pooled,
    'mature sperm': pooled,
    'Medial ganglionic eminence neurons': pooled,
    'medullary thymic epithelial cell immature': pooled,
    'medullary thymic epithelial cell mature': pooled,
    'monocytes': pooled,
    'MPP': pooled,
    'MSC bone': pooled,
    'MSC skin': pooled,
    'MSC thymus': pooled,
    'naive cd4t 24h': pooled,
    'neuron': pooled,
    'NK cells': pooled,
    'NKT stage1': pooled,
    'NKT stage2': pooled,
    'NKT stage3': pooled,
    'oligodendrocyte myelinating': pooled,
    'oligodendrocyte newly formed': pooled,
    'oligodendrocyte precursor': pooled,
    'pancreatic alpha': pooled,
    'pancreatic beta': pooled,
    'pgc female': pooled,
    'pgc male': pooled,
    'preadipocytes white': pooled,
    'prostate luminal cells': pooled,
    'rsEpiSC': pooled,
    'skin': pooled,
    'small intestine cells': pooled,
    'somatic gondal cell': pooled,
    'spermatids': pooled,
    'spermatocytes': pooled,
    'spermatogonia': pooled,
    'SS Early blastocyst E4 C8': single_cell,
    'SS Early blastocyst E2 C16': single_cell,
    'SS Embryo2C early E1 C2': single_cell,
    'SS Embryo2C late E6 C2': single_cell,
    'SS Embryo2C mid E5 C2': single_cell,
    'SS Embryo4C E1 C2': single_cell,
    'SS Embryo8C E1 C1': single_cell,
    'SS Late blastocyst E2 C2': single_cell,
    'SS Late blastocyst E2 C8': single_cell,
    'SS Mid blastocyst E2 C17': single_cell,
    'SS Mid blastocyst E2 C9': single_cell,
    'SS Morula E1 C10': single_cell,
    'SS Zygote E1 C1': single_cell,
    'XEN': pooled,
    'zona limitans intrathalamica': pooled,
    }

if __name__ == '__main__':
    from glbase import glload

    # Check all sample names are actually used:
    expn = glload("../../pub/rsem-genes/genes_cpm_expression.glb")
 
    cond_names = expn.getConditionNames()
    
    print('\nFound in "cell_source" but not in expn:')
    for c in sorted(cell_source.keys()):
        if c not in cond_names:
            print('! %s' % (c,))
            
    print('\nFound in "expn" but not in cell_source:')
    for c in cond_names:
        if c not in list(cell_source.keys()):
            print("'%s': ," % (c,))