

primary_tissue    = 'Primary tissue'
primary_cell_type = 'Primary cells (FACS sorted/magnetically purified)'
invitro_derived   = 'In vitro derived cells'
cultured_cells    = 'Normal (untransformed) cultured cells'

derivation_type = {
    'adipocytes brown': cultured_cells,
    'adipocytes white': cultured_cells,
    'adipose': primary_cell_type,
    'adrenal medulla': primary_tissue,
    'astrocyte': primary_tissue,
    'B active': primary_cell_type,
    'B cells CD19p': primary_cell_type,
    'B cells CD43m': primary_cell_type,
    'B germinal center': primary_cell_type,
    'B naive': primary_cell_type,
    'B resting': primary_cell_type,
    'basophilic erythroblast': primary_cell_type,
    'blastocyst': primary_tissue,
    'BM macrophages': primary_cell_type,
    'BM monocyte': primary_cell_type,
    'BM': primary_tissue,
    'BMDM cpg': invitro_derived,
    'BMDM IL1b': invitro_derived,
    'BMDM lipidA 0m': invitro_derived,
    'BMDM lipidA 360m': invitro_derived,
    'BMDM MALP2': invitro_derived,
    'BMDM pIFNg': invitro_derived,
    'BMDM pIL4': invitro_derived,
    'BMDM pINFa': invitro_derived,
    'BMDM TGFb': invitro_derived,
    'BMDM': invitro_derived,
    'brain': primary_tissue,
    'caecum': primary_tissue,
    'carotid body': primary_tissue,
    'CD4T cells': primary_cell_type,
    'CD4T DPCD3hi': primary_cell_type,
    'CD4T DPCD3lo': primary_cell_type,
    'CD4T iTreg': invitro_derived,
    'CD4T mIL21': primary_cell_type,
    #'CD4T naive acd328': primary_cell_type,
    'CD4T pIL21': primary_cell_type,
    'CD4T Th1': invitro_derived,
    'CD4T Th17': invitro_derived,
    'CD4T Th2': invitro_derived,
    'CD4T Th9': invitro_derived,
    'CD4T Treg': invitro_derived,
    #'CD4Tcd328': primary_cell_type,
    #'CD4Tuntre': primary_cell_type,
    'CD8T il2': primary_cell_type,
    'CD8T nkg2dn': primary_cell_type,
    'CD8T nkg2dp': primary_cell_type,
    #'CD8T untre': primary_cell_type,
    'CD8T': primary_cell_type,
    'cerebellar gran neurons': primary_cell_type,
    'cerebellum': primary_tissue,
    #'cerebral cortex endothelium': primary_tissue,
    #'cerebrum': primary_tissue,
    'chondrocyte rib': primary_cell_type,
    'CLP': primary_cell_type,
    'CMP': primary_cell_type,
    'colon epithelial cells': primary_tissue,
    'colon': primary_tissue,
    'cortex neuron': primary_cell_type,
    'cortex': primary_tissue,
    'cortical thymic epithelial': primary_cell_type,
    #'cranial neural crest mandible': primary_tissue,
    'DC CD11bp': primary_cell_type,
    'DC CD8p': primary_cell_type,
    'dendritic cells': invitro_derived,
    #'dental pulp tissue': primary_tissue,
    'dentate gyrus': primary_tissue,
    'dermal fibroblast': cultured_cells,
    'DN1': primary_cell_type,
    'DN1eP': primary_cell_type,
    'DN1ePNKT': primary_cell_type,
    'DN2a': primary_cell_type,
    'DN2b': primary_cell_type,
    'DN3': primary_cell_type,
    'dorsal rootganglia': primary_cell_type,
    'DP': primary_cell_type,
    'E105 central neural epithelium': primary_tissue,
    'E105 dorsal control neural epithelium': primary_tissue,
    'E105 lateral nasal prominence': primary_tissue,
    'E105 lateral prominence neural epithelium': primary_tissue,
    'E105 mandibular arch': primary_tissue,
    'E105 maxillary arch': primary_tissue,
    #'E105 medial nasal prominence': primary_tissue,
    'E105 olfactory pit': primary_tissue,
    'E125 atrioventricular canal': primary_tissue,
    'E165 cortical neurons': primary_cell_type,
    'E165 skin': primary_tissue,
    'E185 dermis': primary_tissue,
    'E185 epidermis': primary_tissue,
    'E65 Epiblast AD': primary_tissue,
    'E65 Epiblast AP': primary_tissue,
    'E65 Epiblast PD':primary_tissue ,
    'E65 Epiblast PP': primary_tissue,
    'E85 caudal brain neural epithelium': primary_tissue,
    'E85 floor plate': primary_tissue,
    'E85 mesoderm': primary_tissue,
    'E85 non floor plate neural epithelium': primary_tissue,
    'E95 cranial mesenchyme': primary_tissue,
    'E95 epidermal ectoderm': primary_tissue,
    'E95 mandibular arch': primary_tissue,
    'E95 maxillary arch': primary_tissue,
    'ectoplacental cone': primary_tissue,
    'elongative spermatids': primary_cell_type,
    'eos im lm': invitro_derived,
    'eos im lp': invitro_derived,
    'epidermis basal E14': primary_cell_type,
    'epidermis suprabasal E14': primary_cell_type,
    'epididymis': primary_tissue,
    'EpiSC': cultured_cells,
    'erythroblast': primary_cell_type,
    'erythrocytes typeA': primary_cell_type,
    'erythrocytes typeB': primary_cell_type,
    'erythroid progenitor': primary_cell_type,
    'ESC 2iL HVn': cultured_cells,
    'ESC 2iL HVp': cultured_cells,
    'ESC B6J': cultured_cells,
    'ESC groundstate line1': cultured_cells,
    'ESC naive 2iL': cultured_cells,
    'ESC naive 2iLGO': cultured_cells,
    'ESC PDL': cultured_cells,
    'ESC V65': cultured_cells,
    'ESC ZHBTc4': cultured_cells,
    'ESC': cultured_cells,
    'eye': primary_tissue,
    'fatpad': primary_tissue,
    'frontal cortex': primary_tissue,
    #'genital fatpad': primary_tissue,
    'GMP': primary_cell_type,
    'granulocytes': invitro_derived,
    'hair follicle stem cells': primary_cell_type,
    'hair follicle transit amplifying cells':primary_cell_type ,
    'hair follicle': primary_cell_type,
    'heart': primary_tissue,
    'hippocampus neuron': primary_cell_type,
    'hippocampus tissue': primary_tissue,
    'hippocampus': primary_tissue,
    'HSC MPP1': primary_cell_type,
    'HSC MPP2': primary_cell_type,
    'HSC MPP3': primary_cell_type,
    'HSC MPP4': primary_cell_type,
    'HSC': primary_cell_type,
    'ICM E35': primary_cell_type,
    'ICM E375': primary_cell_type,
    'ILC2': primary_cell_type,
    'ileum': primary_tissue,
    'iNKT': primary_cell_type ,
    'intestinal stem cell': primary_tissue,
    'intestinal subepithelial myofibroblasts adult': primary_cell_type,
    'intestinal subepithelial myofibroblasts neonatal': primary_cell_type,
    'intestine': primary_tissue,
    'keratinocytes': cultured_cells,
    'kidney': primary_tissue,
    'large intestine': primary_tissue,
    #'leptotene spermatocytes': primary_cell_type,
    #'liver E1429bkgd': primary_tissue,
    'liver': primary_tissue,
    #'liverE145': primary_tissue,
    'lower molar': primary_tissue,
    'LTHSC': primary_cell_type,
    'lung': primary_tissue,
    'lungFibroblasts': primary_cell_type,
    'mac im lm': primary_cell_type,
    'mac im lp': primary_cell_type,
    'mac ip lm': primary_cell_type,
    'mac ip lp': primary_cell_type,
    'mammary tissue': primary_tissue,
    'mast cells cd25n': primary_cell_type,
    'mast cells cd25p': primary_cell_type,
    'mature sperm': primary_cell_type,
    'Medial ganglionic eminence neurons': primary_cell_type,
    'medullary thymic epithelial cell immature': primary_cell_type,
    'medullary thymic epithelial cell mature': primary_cell_type,
    'medullary thymic epithelial': primary_cell_type,
    'MEF': cultured_cells,
    'megakaryoblast': primary_cell_type,
    'megakryocyte erythroid progenitor': primary_cell_type,
    'microglia': primary_cell_type,
    'monocytes': primary_cell_type,
    'morula': primary_cell_type,
    'motor neurons': primary_cell_type,
    'MPP': primary_cell_type,
    'MSC bone': primary_cell_type,
    'MSC skin': primary_cell_type,
    'MSC thymus': primary_cell_type,
    'mst im lm': invitro_derived,
    'mst im lp': invitro_derived,
    'mst ip lm': invitro_derived,
    'mst ip lp': invitro_derived,
    'myelocytes': primary_cell_type,
    'myeloid': primary_cell_type,
    'myoblast': cultured_cells,
    'naive cd4t 24h': primary_cell_type,
    #'naiveT': primary_cell_type,
    'neocortex cortical plate': primary_tissue,
    'neocortex subventricular zone': primary_tissue,
    'neocortex ventricular zone': primary_tissue,
    'neonatal tail fibroblast': cultured_cells,
    'neu im lm': primary_cell_type,
    'neu im lp': primary_cell_type,
    'neu ip lm': primary_cell_type,
    'neu ip lp': primary_cell_type,
    'neuron': primary_cell_type,
    'NK cells': primary_cell_type,
    'NKT stage1': primary_cell_type,
    'NKT stage2': primary_cell_type,
    'NKT stage3': primary_cell_type,
    'NPC': primary_cell_type,
    'nucleus accumbens': primary_tissue,
    'olfactory bulb': primary_tissue,
    'oligodendrocyte myelinating': primary_cell_type,
    'oligodendrocyte newly formed':primary_cell_type,
    'oligodendrocyte precursor': primary_cell_type,
    'oocytes': primary_cell_type,
    'orthochromatic erythroblast': primary_cell_type,
    'oviduct': primary_tissue,
    #'pachytene spermatocytes': primary_cell_type,
    'pancreatic alpha': primary_cell_type,
    'pancreatic beta': primary_cell_type,
    'patski': cultured_cells,
    'pgc female': primary_cell_type,
    'pgc male': primary_cell_type,
    'pineal gland': primary_tissue,
    'placenta': primary_tissue,
    'polychromatic erythroblast': primary_cell_type,
    'preadipocytes brown': cultured_cells,
    'preadipocytes white': cultured_cells,
    'preB': primary_cell_type,
    #'prim typeA spermatogonia': primary_cell_type,
    'primary adipocytes brown': primary_cell_type,
    'primary adipocytes white': primary_cell_type,
    'proB fracB': primary_cell_type,
    'proB fracCC': primary_cell_type,
    'proB': primary_cell_type,
    'proerythroblast': primary_cell_type,
    'promyelocytes': primary_cell_type,
    'pronuclei': primary_cell_type,
    'prostate basal cells': primary_tissue,
    'prostate luminal cells': primary_tissue,
    'retina': primary_tissue,
    'round spermatids': primary_cell_type,
    'rsEpiSC':  cultured_cells,
    'sdc im lm': primary_cell_type,
    'sdc im lp': primary_cell_type,
    'sdc ip lm': primary_cell_type,
    'sdc ip lp': primary_cell_type,
    'skeletal muscle': primary_tissue,
    'skin epithelial': primary_tissue,
    'small intestine cells': primary_tissue,
    'somatic gondal cell': primary_tissue,
    #'sperm': primary_cell_type,
    'spermatids': primary_cell_type,
    'spermatocytes': primary_cell_type,
    'spermatogonia':primary_cell_type,
    'spinalcord': primary_tissue,
    'spleen': primary_tissue,
    'splenicB cells': primary_cell_type,
    'SS Early blastocyst E2 C16': primary_cell_type,
    'SS Early blastocyst E4 C8': primary_cell_type,
    'SS Embryo2C early E1 C2': primary_cell_type,
    'SS Embryo2C late E6 C2': primary_cell_type,
    'SS Embryo2C mid E5 C2': primary_cell_type,
    'SS Embryo4C E1 C2':primary_cell_type,
    'SS Embryo8C E1 C1': primary_cell_type,
    'SS Late blastocyst E2 C2': primary_cell_type,
    'SS Late blastocyst E2 C8': primary_cell_type,
    'SS Mid blastocyst E2 C17': primary_cell_type,
    'SS Mid blastocyst E2 C9': primary_cell_type,
    'SS Morula E1 C10': primary_cell_type,
    'SS Zygote E1 C1': primary_cell_type,
    'striated muscle': primary_tissue,
    'striatum': primary_tissue,
    'substantia nigra': primary_tissue,
    'subventricularzone': primary_tissue,
    'tail fibroblast': primary_tissue,
    'telencephalon': primary_tissue,
    'TER119p erythroid cells': primary_cell_type,
    'testicular': primary_tissue,
    'thymus': primary_tissue,
    'trophoblast giant cells': primary_cell_type,
    'TSC': cultured_cells,
    #'typeA spermatogonia': primary_cell_type,
    #'typeB spermatogonia': primary_cell_type,
    'upper molar': primary_tissue,
    'uterus': primary_tissue,
    'vas deferens': primary_tissue,
    'ventral tagmental': primary_tissue,
    'white matter glia': primary_cell_type,
    'X2clc': cultured_cells,
    'X2clc D1 rp3': cultured_cells,
    'X2C embryo': primary_cell_type,
    'X4C embryo': primary_cell_type,
    'X8C embryo': primary_cell_type,
    'XEN': cultured_cells,
    'zona limitans intrathalamica': primary_tissue,
    }

if __name__ == '__main__':
    from glbase import glload
    from .gene_layer_name import gene_layer_name

    # Check all sample names are actually used:
    expn = glload("../../pub/rsem-genes/genes_cpm_expression.glb")

    cond_names = expn.getConditionNames()

    print('\nFound in "derivation_type" but not in expn:')
    for c in sorted(derivation_type.keys()):
        if c not in cond_names:
            print('! %s' % (c,))

    print('\nFound in "expn" but not in derivation_type:')
    for c in cond_names:
        if c not in list(derivation_type.keys()):
            print("'%s': ," % (c,))
