# This is the list of raw sample names that are in the published dataset
for_publication = ['B germinal center',
	'B resting',
	'BM macrophages',
	'BM monocyte',
	'BM', 
	'BMDM',
	'BMDM IL1b',
	'BMDM MALP2',
	'BMDM TGFb',
	'BMDM cpg',
	'BMDM lipidA 0m',
	'BMDM lipidA 360m',
	'BMDM pIFNg',
	'BMDM pIL4',
	'BMDM pINFa',
	'B active',
	'B cells CD43m',
	'B cells CD19p',
	'B naive',
	'CD4T Th1',
	'CD4T Th17',
	'CD4T Th2',
	'CD4T Th9',
	'CD4T Treg',
	'CD4T cells',
	'CD4T iTreg',
	'CD4T mIL21',
	'CD4T pIL21',
	'CD4T DPCD3hi', 
	'CD4T DPCD3lo',
	'naive cd4t 24h',
	#'CD4T naive', # Old colour space, omit
	'CD8T il2',
	'CD8T nkg2dn',
	'CD8T nkg2dp',
	'CD8T untre',
	'CD8T',
	'CD8T cells',
	'CLP',
	'CMP',
	'DC CD11bp',
	'DC CD8p',
	'DN1',
	'DN2a',
	'DN2b',
	'DN3',
	'DP',
	'dental pulp tissue',
	'E105 central neural epithelium',
	'E105 dorsal control neural epithelium',
	'E105 lateral prominence neural epithelium',
	'E105 lateral nasal prominence',
	'E105 mandibular arch',
	'E105 maxillary arch',
	'E105 medial nasal prominence',
	'E105 olfactory pit',
	'E165 cortical neurons',
	'E165 skin',
	'E185 dermis',
	'E185 epidermis',
	'E65 Epiblast AD',
	'E65 Epiblast AP',
	'E65 Epiblast PD',
	'E65 Epiblast PP',
	'E85 mesoderm',
	'E85 floor plate',
	'E85 caudal brain neural epithelium',
	'E85 non floor plate neural epithelium',
	'E95 cranial mesenchyme',
	'E95 epidermal ectoderm',
	'E95 mandibular arch',
	'E95 maxillary arch',
	'ESC', 
	'ESC E14',
	'ESC 2iL HVn',
	'ESC 2iL HVp',
	'ESC B6J',
	'ESC PDL',
	'ESC V65',
	'ESC ZHBTc4',
	'ESC naive 2iL',
	'ESC naive 2iLGO',
	'ESC groundstate line1',
	'ESC groundstate line2',
	'ESC groundstate line3',
	'ESC groundstate line4',
	'EpiSC',
	'EpiSC DFN',
	'EpiSC KFN',
	#'Epiblast', I have PP, AP, DP, etc. epiblasts now. This was aligned from FASTA!!
	'GMP',
	'genital fatpad',
	'HSC',
	'HSC MPP1',
	'HSC MPP2',
	'HSC MPP3',
	'HSC MPP4',
	'ICM E35',
	'ICM E375',
	'ILC2',
	'LTHSC',
	'MEF',
	'MPP',
	'Medial ganglionic eminence neurons',
	'NK cells',
	'NPC',
	'SS Early blastocyst E2 C16',
	'SS Early blastocyst E4 C8',
	'SS Embryo2C early E1 C2',
	'SS Embryo2C late E6 C2',
	'SS Embryo2C mid E5 C2',
	'SS Embryo4C E1 C2',
	'SS Embryo8C E1 C1',
	'SS Late blastocyst E2 C2',
	'SS Late blastocyst E2 C8',
	'SS Mid blastocyst E2 C17',
	'SS Mid blastocyst E2 C9',
	'SS Morula E1 C10',
	'SS Zygote E1 C1',
	'spermatogonia',
	'TER119p erythroid cells',
	'TSC',
	'2C embryo',
	'4C embryo',
	'8C embryo',
	'8C embryo SS',
	'embryo 2C', 
	'adipocytes',
	'adipocytes brown',
	'adipocytes white',
	'adipose',
	'astrocyte',
	'basophilic erythroblast',
	'blastocyst',
	'brain',
	'caecum',
	'cerebellar gran neurons',
	'cerebellum',
	'cerebral cortex endothelium',
	#'cerebrum', want ot remove some CS samples, anyway, this is basically whole front brain
	'colon',
	'cortex',
	'cortex neuron',
	'cortical plate',
	'cortical thymic epithelial',
	'cortical thymic epithelial cell',
	'dendritic cells',
	'dentate gyrus',
	'dermal fibroblast',
	'dorsal rootganglia',
	'elongative spermatids',
	'eos im lm',
	'eos im lp',
	'epidermis basal E14',
	'epidermis suprabasal E14',
	'epididymis',
	'erythroblast',
	'erythrocytes typeA',
	'erythrocytes typeB',
	'erythroid progenitor',
	'eye',
	'fatpad',
	'frontal cortex',
	'granulocyte',
	'granulocytes', 
	'granule cells',
	'hair follicle',
	'hair follicle stem cells',
	'hair follicle transit amplifying cells',
	'heart',
	'hippocampus',
	'hippocampus neuron',
	'hippocampus tissue',
	'ileum',
	'intestinal subepithelial myofibroblasts adult',
	'intestinal subepithelial myofibroblasts neonatal',
	'intestine',
	'keratinocytes',
	'kidney',
	'large intestine',
	'leptotene spermatocytes',
	'liver',
	'lower molar',
	'lung',
	'lungFibroblasts',
	'mac im lm',
	'mac im lp',
	'mac ip lm',
	'mac ip lp',
	'mammary tissue',
	'mast cells cd25n',
	'mast cells cd25p',
	'mature sperm',
	'medullary thymic epithelial',
	'medullary thymic epithelial cell',
	'medullary thymic epithelial cell immature',
	'medullary thymic epithelial cell mature',
	'megakaryoblast',
	'megakryocyte erythroid progenitor',
	'microglia',
	'monocytes',
	'morula',
	'motor neurons',
	'mst im lm',
	'mst im lp',
	'mst ip lm',
	'mst ip lp',
	'myelocytes',
	'myeloid',
	'myoblast',
	'neocortex cortical plate',
	'neocortex subventricular zone',
	'neocortex ventricular zone',
	'neonatal tail fibroblast',
	'neu im lm',
	'neu im lp',
	'neu ip lm',
	'neu ip lp',
	'neuron',
	'nucleus accumbens',
	'olfactory bulb',
	'olfactorybulb',
	'oligodendrocyte myelinating',
	'oligodendrocyte newly formed',
	'oligodendrocyte precursor',
	'oocyte',
	'oocytes',
	'orthochromatic erythroblast',
	'oviduct',
	'pachytene spermatocytes',
	'pancreatic alpha', 
	'pancreatic beta',
	'patski',
	'pgc',
	'pgc female',
	'pgc male',
	'pineal gland',
	'placenta',
	'polychromatic erythroblast',
	'preB',
	'preadipocytes brown',
	'preadipocytes white',
	'prim typeA spermatogonia',
	'primary adipocytes brown',
	'primary adipocytes white',
	'proB',
	'proB fracB',
	'proB fracCC',
	'proerythroblast',
	'promyelocytes',
	'pronuclei',
	'prostate basal cells',
	'prostate luminal cells',
	#'quadriceps',
	'retina',
	'round spermatids',
	'rsEpiSC',
	'skin',
	'sdc im lm',
	'sdc im lp',
	'sdc ip lm',
	'sdc ip lp',
	'skeletal muscle',
	'skin epithelial',
	'somatic gondal cell',
	'sperm',
	'spermatids',
	'spermatocytes',
	'spinalcord',
	'spinal cord',
	'spleen',
	'splenicB cells',
	#'striatal neurons', # MEFs
	'striated muscle',
	'striatum',
	'substantia nigra',
	'subventricularzone',
	'tail fibroblast',
	'telencephalon',
	'testicular',
	'thymus',
	'trophoblast giant cells',
	'typeA spermatogonia',
	'typeB spermatogonia',
	'upper molar',
	'uterus',
	'vas deferens',
	'ventral tagmental',
	'white matter glia',
	'ventrical zone tissue',
	'zona limitans intrathalamica',
	'iNKT',
	'XEN',
	'cranial neural crest mandible',
	'chondrocyte rib',
	'ectoplacental cone',
	'DN1eP',
	'DN1ePNKT',
	'NKT stage1',
	'NKT stage2',
	'NKT stage3',
    'carotid body',
    'adrenal medulla',
    'E125 atrioventricular canal',
    'intestinal stem cell',
    'small intestine cells',
    'colon epithelial cells',
    'MSC bone',
    'MSC skin',
    'MSC thymus'
    ]