

# See also: http://en.wikipedia.org/wiki/Cell_type
gene_layer_name = {'Embryonic':
        ['ESC',
        'ESC V65',
        'ESC ZHBTc4',
        'ESC B6J',
        'TSC',
        'trophoblast giant cells',
        'blastocyst',
        'ICM E375',
        'oocytes',
        'placenta',
        'ICM E35',
        'EpiSC',
        'X2C embryo',
        'X4C embryo',
        'X8C embryo',
        'morula',
        'SS Early blastocyst E4 C8',
        'SS Embryo8C E1 C1',
        'SS Zygote E1 C1',
        'pronuclei',
        'SS Early blastocyst E2 C16',
        'SS Embryo2C early E1 C2',
        'SS Embryo2C late E6 C2',
        'SS Embryo2C mid E5 C2',
        'SS Embryo4C E1 C2',
        'SS Late blastocyst E2 C2',
        'SS Late blastocyst E2 C8',
        'SS Mid blastocyst E2 C17',
        'SS Mid blastocyst E2 C9',
        'SS Morula E1 C10',
        'ESC 2iL HVn',
        'ESC 2iL HVp',
        'ESC PDL',
        'ESC groundstate line1',
        'ESC naive 2iL',
        'ESC naive 2iLGO',
        'E65 Epiblast AD',
        'E65 Epiblast AP',
        'E65 Epiblast PD',
        'E65 Epiblast PP',
        'XEN',
        'rsEpiSC',
        'pgc female',
        'pgc male',
        'ectoplacental cone',
        'X2clc',
        'X2clc D1 rp3',
        ],
    'Germ cells':
        [
        'testicular',
        'round spermatids',
        'elongative spermatids',
        'spermatids',
        'mature sperm',
        'spermatogonia',
        'spermatocytes',
        ],
    'Blood mesoderm':
        [
        'BM',
        'CD4T DPCD3hi',
        'CD4T DPCD3lo',
        'CD4T cells',
        'CD8T nkg2dn',
        'CD8T nkg2dp',
        'CLP',
        'CMP',
        'DN1eP',
        'DN1ePNKT',
        'GMP',
        'HSC MPP1',
        'HSC MPP2',
        'HSC MPP3',
        'HSC MPP4',
        'LTHSC',
        'MPP',
        'NK cells',
        'NKT stage1',
        'NKT stage2',
        'NKT stage3',
        'erythrocytes typeA',
        'erythrocytes typeB',
        'granulocytes',
        'iNKT',
        'mast cells cd25n',
        'mast cells cd25p',
        'naive cd4t 24h',
        'eos im lm', 'eos im lp','mac im lm','mac im lp','mac ip lm',
        'mac ip lp', 'BM macrophages', 'BMDM', 'BMDM cpg', 'BMDM IL1b', 'BMDM pIFNg',
        'BMDM MALP2', 'BMDM pIL4', 'BMDM pINFa', 'BMDM TGFb',
        'CD4T Treg',
        'CD4T iTreg',
        'CD4T mIL21', 'CD4T pIL21', 'CD4T Th17', 'CD4T Th1',
        'CD4T Th2',
        'CD4T Th9',
        'CD8T',
        'CD8T il2',
        'dendritic cells',
        'preB', 'proB', 'spleen', 'B cells CD43m', 'B cells CD19p',
        'thymus','mst im lm', 'mst im lp', 'mst ip lm',
        'mst ip lp', 'neu im lm', 'neu im lp', 'neu ip lm',
        'neu ip lp',
        'proB fracB', 'proB fracCC', 'BMDM lipidA 0m', 'BMDM lipidA 360m',
        'splenicB cells', 'promyelocytes',
        'erythroblast', 'megakaryoblast', 'megakryocyte erythroid progenitor',
        'TER119p erythroid cells',
        'sdc im lm',
        'sdc im lp',
        'sdc ip lm',
        'sdc ip lp',
        'B germinal center',
        'B active',
        'B naive',
        'DN1',
        'DN2a', 'DN2b', 'DN3',
        'myelocytes',
        'B resting', 'DP',
        'HSC',
        'myeloid', 'erythroid progenitor',
        'basophilic erythroblast', 'BM monocyte',
        'ILC2', 'microglia', 'orthochromatic erythroblast', 'polychromatic erythroblast',
        'proerythroblast', 'DC CD11bp', 'DC CD8p',
        'monocytes',
        ],
    'Endoderm':
        ['intestine',
        'liver',
        'lung',
        'ileum',
        'large intestine',
        'colon',
        'caecum',
        'prostate basal cells',
        'medullary thymic epithelial',
        'medullary thymic epithelial cell immature',
        'medullary thymic epithelial cell mature',
        'pancreatic alpha',
        'pancreatic beta',
        'intestinal stem cell',
        'colon epithelial cells',
        'small intestine cells',
        'prostate luminal cells',
        ],
    'Mesoderm':
        [
        'adipocytes brown',
        'adipocytes white',
        'adipose',
        'E125 atrioventricular canal',
        'carotid body',
        'cortical thymic epithelial',
        'dermal fibroblast',
        'epididymis',
        'heart',
        'intestinal subepithelial myofibroblasts adult',
        'intestinal subepithelial myofibroblasts neonatal',
        'lungFibroblasts',
        'mammary tissue',
        'MEF',
        'myoblast',
        'neonatal tail fibroblast',
        'oviduct',
        'preadipocytes brown',
        'preadipocytes white',
        'primary adipocytes brown',
        'primary adipocytes white',
        'skeletal muscle',
        'striated muscle',
        'somatic gondal cell',
        'tail fibroblast',
        'uterus',
        'vas deferens',
        'MSC bone',
        'MSC skin',
        'MSC thymus',
        'chondrocyte rib',
        'patski', # Patski = Kidney fibroblast embryonic
        'adrenal medulla', # This is part of the kidneys and endocrine.
        'kidney',
        'fatpad',
        ],
    'Neurectoderm':
        ['cerebellum',
        'cortex',
        'cortex neuron',
        'hippocampus neuron',
        'hippocampus',
        'hippocampus tissue',
        'NPC',
        'E165 cortical neurons',
        'brain',
        'cerebellar gran neurons',
        'dentate gyrus',
        'dorsal rootganglia',
        'eye',
        'motor neurons',
        'neocortex cortical plate',
        'neocortex subventricular zone',
        'neocortex ventricular zone',
        'retina',
        'striatum',
        'substantia nigra',
        'subventricularzone',
        'telencephalon',
        'ventral tagmental',
        'pineal gland', #?!?!?!
        'frontal cortex',
        'olfactory bulb',
        'nucleus accumbens',
        'white matter glia',
        'oligodendrocyte myelinating',
        'oligodendrocyte newly formed',
        'oligodendrocyte precursor',
        'spinalcord',
        'Medial ganglionic eminence neurons',
        'astrocyte',
        'neuron',
        'zona limitans intrathalamica',
        ],
    'Neural crest':
        ['lower molar',
        'upper molar',
        'E85 floor plate',
        'E85 mesoderm',
        'E105 central neural epithelium',
        'E105 dorsal control neural epithelium',
        'E105 lateral prominence neural epithelium',
        'E105 mandibular arch',
        'E105 maxillary arch',
        'E85 caudal brain neural epithelium',
        'E85 non floor plate neural epithelium',
        'E95 cranial mesenchyme',
        'E95 epidermal ectoderm',
        'E95 mandibular arch',
        'E95 maxillary arch',
        'E105 lateral nasal prominence',
        'E105 olfactory pit',
        #'cranial neural crest mandible',
        ],
    'Surface ectoderm': # Surface ectoderm
        ['E185 dermis',
        'E185 epidermis',
        'E165 skin',
        'keratinocytes',
        'epidermis basal E14',
        'epidermis suprabasal E14',
        'hair follicle',
        'skin epithelial',
        'hair follicle stem cells',
        'hair follicle transit amplifying cells',
        ]}

if __name__ == '__main__':
    from glbase import glload
    #from sample_description import sample_description

    # Check all sample names are actually used:
    expn = glload("../../pub/rsem-genes/genes_cpm_expression.glb")

    cond_names = expn.getConditionNames()

    all_keys = []
    for k in gene_layer_name:
        all_keys += gene_layer_name[k]

    print('\nFound in "gene_layer_name" but not in expn:')
    for c in sorted(all_keys):
        if c not in cond_names:
            print('! %s' % (c,))

    print('\nFound in "expn" but not in gene_layer_name:')
    for c in sorted(cond_names):
        if c not in all_keys:
            print("'%s'" % (c,))
