
# Auto-generated code by get_tag_counts.py

num_replicates = {
    "B active": 4,
    "B cells CD19p": 6,
    "B cells CD43m": 12,
    "B germinal center": 2,
    "B naive": 4,
    "B resting": 4,
    "BM": 2,
    "BM macrophages": 4,
    "BM monocyte": 3,
    "BMDM": 3,
    "BMDM IL1b": 1,
    "BMDM MALP2": 1,
    "BMDM TGFb": 1,
    "BMDM cpg": 1,
    "BMDM lipidA 0m": 1,
    "BMDM lipidA 360m": 1,
    "BMDM pIFNg": 1,
    "BMDM pIL4": 1,
    "BMDM pINFa": 1,
    "CD4T DPCD3hi": 2,
    "CD4T DPCD3lo": 2,
    "CD4T Th1": 6,
    "CD4T Th17": 3,
    "CD4T Th2": 6,
    "CD4T Th9": 1,
    "CD4T Treg": 1,
    "CD4T cells": 4,
    "CD4T iTreg": 2,
    "CD4T mIL21": 1,
    "CD4T pIL21": 1,
    "CD8T": 6,
    "CD8T il2": 1,
    "CD8T nkg2dn": 3,
    "CD8T nkg2dp": 3,
    "CLP": 4,
    "CMP": 4,
    "DC CD11bp": 1,
    "DC CD8p": 1,
    "DN1": 2,
    "DN1eP": 4,
    "DN1ePNKT": 4,
    "DN2a": 2,
    "DN2b": 3,
    "DN3": 2,
    "DP": 4,
    "E105 central neural epithelium": 1,
    "E105 dorsal control neural epithelium": 1,
    "E105 lateral nasal prominence": 1,
    "E105 lateral prominence neural epithelium": 1,
    "E105 mandibular arch": 1,
    "E105 maxillary arch": 1,
    "E105 olfactory pit": 1,
    "E125 atrioventricular canal": 4,
    "E165 cortical neurons": 3,
    "E165 skin": 2,
    "E185 dermis": 1,
    "E185 epidermis": 1,
    "E65 Epiblast AD": 1,
    "E65 Epiblast AP": 1,
    "E65 Epiblast PD": 1,
    "E65 Epiblast PP": 1,
    "E85 caudal brain neural epithelium": 1,
    "E85 floor plate": 1,
    "E85 mesoderm": 1,
    "E85 non floor plate neural epithelium": 1,
    "E95 cranial mesenchyme": 1,
    "E95 epidermal ectoderm": 1,
    "E95 mandibular arch": 1,
    "E95 maxillary arch": 1,
    "ESC": 7,
    "ESC 2iL HVn": 2,
    "ESC 2iL HVp": 2,
    "ESC B6J": 1,
    "ESC PDL": 3,
    "ESC V65": 2,
    "ESC ZHBTc4": 1,
    "ESC groundstate line1": 4,
    "ESC naive 2iL": 3,
    "ESC naive 2iLGO": 3,
    "EpiSC": 11,
    "GMP": 4,
    "HSC": 16,
    "HSC MPP1": 3,
    "HSC MPP2": 3,
    "HSC MPP3": 3,
    "HSC MPP4": 3,
    "ICM E35": 2,
    "ICM E375": 1,
    "ILC2": 2,
    "LTHSC": 1,
    "MEF": 4,
    "MPP": 2,
    "MSC bone": 9,
    "MSC skin": 13,
    "MSC thymus": 8,
    "Medial ganglionic eminence neurons": 1,
    "NK cells": 2,
    "NKT stage1": 5,
    "NKT stage2": 7,
    "NKT stage3": 6,
    "NPC": 2,
    "SS Early blastocyst E2 C16": 14,
    "SS Early blastocyst E4 C8": 11,
    "SS Embryo2C early E1 C2": 3,
    "SS Embryo2C late E6 C2": 6,
    "SS Embryo2C mid E5 C2": 5,
    "SS Embryo4C E1 C2": 13,
    "SS Embryo8C E1 C1": 32,
    "SS Late blastocyst E2 C2": 9,
    "SS Late blastocyst E2 C8": 6,
    "SS Mid blastocyst E2 C17": 13,
    "SS Mid blastocyst E2 C9": 28,
    "SS Morula E1 C10": 37,
    "SS Zygote E1 C1": 4,
    "TER119p erythroid cells": 1,
    "TSC": 2,
    "X2C embryo": 6,
    "X4C embryo": 3,
    "X8C embryo": 3,
    "XEN": 6,
    "adipocytes brown": 2,
    "adipocytes white": 1,
    "adipose": 2,
    "adrenal medulla": 3,
    "astrocyte": 2,
    "basophilic erythroblast": 3,
    "blastocyst": 1,
    "brain": 3,
    "caecum": 3,
    "carotid body": 3,
    "cerebellar gran neurons": 4,
    "cerebellum": 4,
    "chondrocyte rib": 4,
    "colon": 3,
    "colon epithelial cells": 3,
    "cortex": 5,
    "cortex neuron": 7,
    "cortical thymic epithelial": 3,
    "dendritic cells": 1,
    "dentate gyrus": 5,
    "dermal fibroblast": 1,
    "dorsal rootganglia": 6,
    "ectoplacental cone": 2,
    "elongative spermatids": 2,
    "eos im lm": 2,
    "eos im lp": 2,
    "epidermis basal E14": 2,
    "epidermis suprabasal E14": 2,
    "epididymis": 1,
    "erythroblast": 4,
    "erythrocytes typeA": 2,
    "erythrocytes typeB": 1,
    "erythroid progenitor": 1,
    "eye": 6,
    "fatpad": 2,
    "frontal cortex": 12,
    "granulocytes": 6,
    "hair follicle": 1,
    "hair follicle stem cells": 2,
    "hair follicle transit amplifying cells": 2,
    "heart": 4,
    "hippocampus": 1,
    "hippocampus neuron": 12,
    "hippocampus tissue": 3,
    "iNKT": 1,
    "ileum": 2,
    "intestinal stem cell": 2,
    "intestinal subepithelial myofibroblasts adult": 1,
    "intestinal subepithelial myofibroblasts neonatal": 1,
    "intestine": 2,
    "keratinocytes": 2,
    "kidney": 6,
    "large intestine": 18,
    "liver": 5,
    "lower molar": 1,
    "lung": 5,
    "lungFibroblasts": 2,
    "mac im lm": 2,
    "mac im lp": 2,
    "mac ip lm": 2,
    "mac ip lp": 2,
    "mammary tissue": 1,
    "mast cells cd25n": 2,
    "mast cells cd25p": 2,
    "mature sperm": 1,
    "medullary thymic epithelial": 3,
    "medullary thymic epithelial cell immature": 2,
    "medullary thymic epithelial cell mature": 2,
    "megakaryoblast": 1,
    "megakryocyte erythroid progenitor": 6,
    "microglia": 3,
    "monocytes": 4,
    "morula": 3,
    "motor neurons": 4,
    "mst im lm": 2,
    "mst im lp": 2,
    "mst ip lm": 2,
    "mst ip lp": 2,
    "myelocytes": 1,
    "myeloid": 3,
    "myoblast": 2,
    "naive cd4t 24h": 1,
    "neocortex cortical plate": 5,
    "neocortex subventricular zone": 5,
    "neocortex ventricular zone": 5,
    "neonatal tail fibroblast": 2,
    "neu im lm": 2,
    "neu im lp": 2,
    "neu ip lm": 2,
    "neu ip lp": 2,
    "neuron": 2,
    "nucleus accumbens": 3,
    "olfactory bulb": 5,
    "oligodendrocyte myelinating": 2,
    "oligodendrocyte newly formed": 2,
    "oligodendrocyte precursor": 2,
    "oocytes": 7,
    "orthochromatic erythroblast": 3,
    "oviduct": 1,
    "pancreatic alpha": 2,
    "pancreatic beta": 2,
    "patski": 7,
    "pgc female": 1,
    "pgc male": 2,
    "pineal gland": 2,
    "placenta": 5,
    "polychromatic erythroblast": 3,
    "preB": 1,
    "preadipocytes brown": 2,
    "preadipocytes white": 1,
    "primary adipocytes brown": 1,
    "primary adipocytes white": 1,
    "proB": 2,
    "proB fracB": 2,
    "proB fracCC": 2,
    "proerythroblast": 3,
    "promyelocytes": 1,
    "pronuclei": 3,
    "prostate basal cells": 6,
    "prostate luminal cells": 5,
    "retina": 2,
    "round spermatids": 2,
    "rsEpiSC": 2,
    "sdc im lm": 2,
    "sdc im lp": 2,
    "sdc ip lm": 2,
    "sdc ip lp": 2,
    "skeletal muscle": 3,
    "skin epithelial": 1,
    "small intestine cells": 2,
    "somatic gondal cell": 1,
    "spermatids": 5,
    "spermatocytes": 5,
    "spermatogonia": 1,
    "spinalcord": 4,
    "spleen": 5,
    "splenicB cells": 4,
    "striated muscle": 2,
    "striatum": 2,
    "substantia nigra": 3,
    "subventricularzone": 4,
    "tail fibroblast": 1,
    "telencephalon": 3,
    "testicular": 4,
    "thymus": 1,
    "trophoblast giant cells": 1,
    "upper molar": 1,
    "uterus": 1,
    "vas deferens": 1,
    "ventral tagmental": 3,
    "white matter glia": 2,
    "zona limitans intrathalamica": 1,
    }
