
GAII = 'Illumina Genome Analyzer II'
GAIIx = 'Illumina Genome Analyzer IIx'
hiseq2500 = 'Illumina HiSeq 2500'
hiseq2000 = 'Illumina HiSeq 2000'
hiseq1500 = 'Illumina HiSeq 1500'
hiseq1000 = 'Illumina HiSeq 1000'
MiSeq = 'Illumina MiSeq'

rnaseq_library_parameters = {
    "adipocytes brown": [('single-end', 36, 'RNA-Seq', 'size fractionation', 'Illumina Genome Analyzer')],
    "adipocytes": [('single-end', 36, 'RNA-Seq', 'size fractionation', 'Illumina Genome Analyzer')],
    "adipose": [('single-end', 30, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "B germinal center": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "B resting": [('paired-end', 100, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "B active": [('single-end', 51, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "basophilic erythroblast": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000'), ('single-end', 51, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "B cells CD43m": [('single-end', 50, 'RNA-Seq', 'cDNA',  'AB SOLiD System')],
    "B cells CD19p": [('single-end', 50, 'RNA-Seq', 'cDNA',  'AB SOLiD System')],
    "blastocyst": [('single-end', 50, 'RNA-Seq', 'cDNA','Illumina HiSeq 2000')],
    "BM monocyte": [('paired-end', 100, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "BM": [('single-end', 30, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],  #(Illumina Genome Analyzer II/Illumina HiSeq 2000/cs)
    "BMDM cpg": [('single-end', 50, 'RNA-Seq', 'cDNA',  'Illumina Genome Analyzer II')],
    "BMDM IL1b": [('single-end', 50, 'RNA-Seq', 'cDNA',  'Illumina Genome Analyzer II')],
    "BMDM lipidA 0m": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "BMDM lipidA 360m": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "BMDM MALP2": [('single-end', 50, 'RNA-Seq', 'cDNA',  'Illumina Genome Analyzer II')],
    "BMDM pIFNg": [('single-end', 50, 'RNA-Seq', 'cDNA',  'Illumina Genome Analyzer II')],
    "BMDM pIL4": [('single-end', 50, 'RNA-Seq', 'cDNA',  'Illumina Genome Analyzer II')],
    "BMDM pINFa": [('single-end', 50, 'RNA-Seq', 'cDNA',  'Illumina Genome Analyzer II')],
    "BMDM TGFb": [('single-end', 50, 'RNA-Seq', 'cDNA',  'Illumina Genome Analyzer II')],
    "BMDM": [('single-end', 30, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000'), ('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer II')],
    "B naive": [('single-end', 51, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "brain": [('paired-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000'), ('single-end', 80, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000'), ('single-end', 40, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "Caecum": [('paired-end', 101, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000'), ('paired-end', 80, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "cardiac precursors": [('single-end', 36, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx')],
    "cardiomyocytes": [('single-end', 36, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx')],
    "CD4T cd328": [('paired-end', 90, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "CD4T iTreg": [('single-end', 35, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer II'), ('single-end', 36, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer II')],
    "CD4T mIL21": [('single-end', 36, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer II')],
    "CD4T pIL21": [('single-end', 36, 'RNA-Seq', 'cDNA',  'Illumina Genome Analyzer II')],
    "CD4T Th1": [('single-end', 36, 'RNA-Seq', 'cDNA',  'Illumina Genome Analyzer II'), ('single-end', 50, 'RNA-Seq', 'cDNA',  'Illumina HiSeq 2000'), ('single-end', 100, 'RNA-Seq', 'cDNA',  'Illumina HiSeq 2000')],
    "CD4T Th17": [('single-end', 36, 'RNA-Seq', 'cDNA',  'Illumina Genome Analyzer II'), ('single-end', 50, 'RNA-Seq', 'cDNA',  'Illumina HiSeq 2000')],
    "CD4T Th2": [('single-end', 36, 'RNA-Seq', 'cDNA',  'Illumina Genome Analyzer II'), ('single-end', 50, 'RNA-Seq', 'cDNA',  'Illumina HiSeq 2000'), ('single-end', 41, 'RNA-Seq', 'cDNA',  'Illumina Genome Analyzer IIx'), ('single-end', 100, 'RNA-Seq', 'cDNA',  'Illumina HiSeq 2000'), ('single-end', 36, 'RNA-Seq', 'cDNA',  'Illumina Genome Analyzer IIx')],
    "CD4T Th9": [('single-end', 50, 'RNA-Seq', 'cDNA',  'Illumina HiSeq 2000')],
    "CD4T Treg": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "CD4T untre": [('paired-end', 90, 'RNA-Seq', 'cDNA',  'Illumina HiSeq 2000')],     
    "CD8T il2": [('single-end', 50, 'RNA-Seq', 'cDNA',  'Illumina HiSeq 2000')],     
    "CD8T untre": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],      
    "cerebellar gran neurons": [('single-end', 52, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer II')],
    "cerebellum": [('single-end', 36, 'RNA-Seq', 'cDNA', ' Illumina Genome Analyzer II'), ('single-end', 36, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "cerebrum": [('single-end', 50, 'RNA-Seq', 'cDNA',  'AB SOLiD System')],
    "colon": [('paired-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000'), ('single-end', 80, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000'), ('single-end', 40, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000'), ('paired-end', 101, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "cortex neuron": [('paired-end', 101, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000'), ('paired-end', 101, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2500')],
    "cortex": [('single-end', 36, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer II')],     
    "cortical thymic epithelial": [('paired-end', 100, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "DC CD11bp": [('single-end', 29, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx')],
    "DC CD8p": [('single-end', 29, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx')],
    "dendritic cells": [('single-end', 76, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer II')],
    "dentate gyrus": [('paired-end', 85, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000'), ('paired-end', 100, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000'), ('paired-end', 97, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "dermal fibroblast": [('single-end', 102, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "DN1": [('single-end', 38, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer II')],
    "DN2a": [('single-end', 38, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer II')],
    "DN2b": [('single-end', 38, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer II')],
    "DN3": [('single-end', 38, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer II')],
    "dorsal rootganglia": [('single-end', 52, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer II')],
    "DP": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000'), ('single-end', 38, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer II')],
    "E105 central neural epithelium": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2500')],
    "E105 dorsal control neural epithelium": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2500')],
    "E105 forelimb": [('single-end', 35, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx')],
    "E105 hindlimb": [('single-end', 35, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx')],
    "E105 lateral prominence neural epithelium": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2500')],
    "E105 mandibular arch": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2500')],
    "E105 maxillary arch": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2500')],
    "E105 medial nasal prominence": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2500')],
    "E165 cortical neurons": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "E185 dermis": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "E185 epidermis": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "E165 skin": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "E85 caudal brain neural epithelium": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2500')],
    "E85 non floor plate neural epithelium": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2500')],
    "E95 cranial mesenchyme": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2500')],
    "E95 epidermal ectoderm": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2500')],
    "E95 mandibular arch": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2500')],
    "E95 maxillary arch": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2500')],
    "Early blastocyst E2 C16": [('single-end', 51, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "Early blastocyst E4 C8": [('single-end', 53, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "elongative spermatids": [('single-end', 100, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer II')],
    "Embryo2C early E1 C2": [('single-end', 53, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "Embryo2C late E6 C2": [('single-end', 59, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "Embryo2C mid E5 C2": [('single-end', 46, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "Embryo4C E1 C2": [('single-end', 53, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "Embryo8C E1 C1": [('single-end', 53, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "eos im lm": [('paired-end', 90, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "eos im lp": [('paired-end', 90, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],    
    "Epiblast": [('FASTA', 100, 'RNA-Seq', 'cDNA', 'AB SOLiD System')],   
    "epidermis basal E14": [('single-end', 80, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx'), ('single-end', 96, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "epidermis suprabasal E14": [('single-end', 80, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx'), ('single-end', 96, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "epididymis": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "EpiSC": [('paired-end', 100, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000'), ('paired-end', 50, 'RNA-Seq', 'cDNA', hiseq2500)],
    "erythroblast": [('single-end', 99, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000'), ('single-end', 51, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx')],      
    "erythroid progenitor": [('single-end', 51, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx')],
    "ESC 2iL HVn": [('single-end', 50, 'RNA-Seq', 'cDNA', 'AB SOLiD 4 System')],
    "ESC 2iL HVp": [('single-end', 50, 'RNA-Seq', 'cDNA', 'AB SOLiD 4 System')],
    "ESC B6J": [('single-end', 36, 'RNA-Seq', 'RANDOM', 'Illumina Genome Analyzer II')],
    "ESC V65": [('single-end', 35, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx')],
    "ESC ZHBTc4": [('single-end', 40, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "ESC": [('single-end', 30, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "eye": [('single-end', 76, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx'), ('single-end', 54, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx')],
    "fatpad": [('single-end', 50, 'RNA-Seq', 'cDNA',  'AB SOLiD System')],
    "frontal cortex": [('single-end', 100, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "GenitalFatPad": [('single-end', 50, 'RNA-Seq', 'cDNA',  'AB SOLiD System')],
    "granulocytes": [('single-end', 65, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx')],
    "hair follicle": [('single-end', 80, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx')],
    "heart": [('single-end', 36, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer II'), ('single-end', 36, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx'), ('paired-end', 40, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "hippocampus neuron": [('paired-end', 101, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000'), ('paired-end', 101, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2500')],
    "hippocampus tissue": [('paired-end', 100, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000'), ('paired-end', 101, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "hippocampus": [('single-end', 100, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "HSC": [('paired-end', 36, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 1500'), ('paired-end', 100, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 1500'), ('paired-end', 101, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 1500'), ('paired-end', 49, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 1500'), ('paired-end', 43, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 1500'), ('paired-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 1500')],
    "ICM E35": [('paired-end', 104, 'RNA-Seq', 'RT-PCR', 'Illumina HiSeq 2000')],
    "ICM E375": [('single-end', 50, 'RNA-Seq', 'cDNA','AB SOLiD System 3.0')],
    "ILC2": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "ileum": [('paired-end', 101, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "Intestinal subepithelial myofibroblasts adult": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "Intestinal subepithelial myofibroblasts neonatal": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "intestine": [('single-end', 36, 'RNA-Seq', 'other', 'Illumina HiSeq 2000'), ('single-end', 29, 'RNA-Seq', 'other', 'Illumina HiSeq 2000')],
    "keratinocytes": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx')],
    "kidney": [('paired-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000'), ('paired-end', 80, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000'), ('paired-end', 36, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx'), ('single-end', 36, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer II')],
    "Late blastocyst E2 C2": [('single-end', 53, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')], 
    "Late blastocyst E2 C8": [('single-end', 53, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "leptotene spermatocytes": [('single-end', 100, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer II')],
    "LgIntestine": [('single-end', 50, 'RNA-Seq', 'cDNA', 'AB SOLiD System'), ('single-end',50 , 'RNA-Seq', 'cDNA', 'AB SOLiD System')],
    "liver E1429bkgd": [('single-end', 50, 'RNA-Seq', 'cDNA',  'AB SOLiD System')],
    "liver": [('single-end', 36, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer II'), ('paired-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000'), ('paired-end', 80, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000'), ('paired-end', 40, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "liverE145": [('single-end', 36, 'RNA-Seq', 'other',  'AB SOLiD System'), ('single-end', 50, 'RNA-Seq', 'cDNA',  'AB SOLiD System')],
    "lower molar": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "lung": [('single-end', 36, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer II'), ('paired-end', 36, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx'), ('paired-end', 80, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000'), ('paired-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "lungFibroblasts": [('paired-end', 76, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer II')],
    "mac im lm": [('paired-end', 90, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "mac im lp": [('paired-end', 90, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "mac ip lm": [('paired-end', 90, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "mac ip lp": [('paired-end', 90, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "mammary tissue": [('single-end', 76, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "Matrue sperm": [('single-end', 36, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer II')],
    "medullary thymic epithelial": [('paired-end', 100, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "MEF": [('single-end', 36, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer II')],
    "megakaryoblast": [('single-end', 99, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "megakryocyte erythroid progenitor": [('single-end', 99, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000'), ('single-end', 49, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 1500'), ('single-end', 43, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 1500')],
    "mesodermal cells": [('paired-end', 36, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx')],
    "microglia": [('paired-end', 100, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000'), ('single-end', 32, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "Mid blastocyst E2 C17": [('single-end', 53, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "Mid blastocyst E2 C9": [('single-end', 53, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "Morula E1 C10": [('single-end', 53, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "morula": [('paired-end', 90, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "motor neurons": [('single-end', 74, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx'),  ('paired-end', 100, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "mst im lm": [('paired-end', 90, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "mst im lp": [('paired-end', 90, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "mst ip lm": [('paired-end', 90, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "mst ip lp": [('paired-end', 90, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "myelocytes": [('single-end', 65, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx')],
    "myeloid": [('single-end', 40, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "myoblast": [('single-end', 80, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx')],
    "naive cd4t 24h": [('paired-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "naiveT": [('single-end', 50, 'RNA-Seq', 'cDNA',  'AB SOLiD System')],
    "neocortex cortical plate": [('single-end', 75, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx')],
    "neocortex subventricular zone": [('single-end', 75, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx')],
    "neocortex ventricular zone": [('single-end', 75, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx')],
    "neonatal tail fibroblast": [('single-end', 36, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx')],
    "neu im lm": [('paired-end', 90, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "neu im lp": [('paired-end', 90, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "neu ip lm": [('paired-end', 90, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "neu ip lp": [('paired-end', 90, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "Neuron NCAMp": [('single-end', 38, 'RNA-Seq', 'cDNA',  'Illumina Genome Analyzer IIx')],
    "NPC": [('paired-end', 76, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer II')],
    "nucleus accumbens": [('single-end', 101, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "olfactory bulb": [('paired-end', 35, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx'), ('paired-end', 85, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx'), ('paired-end', 100, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx')],
    "oocytes": [('single-end', 85, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer II')],
    "orthochromatic erythroblast": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000'), ('single-end', 51, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "oviduct": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "pachytene spermatocytes": [('single-end', 100, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer II')],
    "patski": [('single-end', 50, 'RNA-Seq', 'cDNA','AB SOLiD System')],
    "pgc": [('single-end', 101, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "pineal gland": [('single-end', 76, 'RNA-Seq', 'other', 'Illumina Genome Analyzer IIx')],
    "placenta": [('single-end', 36, 'RNA-Seq', 'other', 'Illumina HiSeq 2000'), ('single-end', 50, 'RNA-Seq', 'other', 'AB SOLiD System 3.0')],     
    "polychromatic erythroblast": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000'), ('single-end', 51, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "preadipocytes brown": [('single-end', 36, 'RNA-Seq', 'size fractionation', 'Illumina Genome Analyzer')],
    "preadipocytes": [('single-end', 36, 'RNA-Seq', 'size fractionation', 'Illumina Genome Analyzer')],
    "preB": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "prim typeA spermatogonia": [('single-end', 100, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer II')],
    "primary adipocytes brown": [('single-end', 36, 'RNA-Seq', 'size fractionation', 'Illumina Genome Analyzer')],
    "primary adipocytes white": [('single-end', 36, 'RNA-Seq', 'size fractionation', 'Illumina Genome Analyzer')],
    "proB fracB": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "proB fracCC": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "proB": [('single-end', 96, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000'), ('single-end', 46, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000'), ('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "proerythroblast": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000'), ('single-end', 51, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "promyelocytes": [('single-end', 65, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx')],
    "pronuclei": [('paired-end', 90, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "prostate basal cells": [('single-end', 61, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "retina": [('single-end', 76, 'RNA-Seq', 'other', 'Illumina Genome Analyzer IIx')],
    "round spermatids": [('single-end', 100, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer II')],
    "sdc im lm": [('paired-end', 90, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "sdc im lp": [('paired-end', 90, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "sdc ip lm": [('paired-end', 90, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "sdc ip lp": [('paired-end', 90, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "skeletal muscle": [('paired-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000'), ('paired-end', 50, 'RNA-Seq', 'cDNA', 'AB SOLiD System 3.0'), ('paired-end', 36, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx')],
    "skin epithelial": [('single-end', 100, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "sperm": [('single-end', 36, 'RNA-Seq', 'RANDOM', 'Illumina Genome Analyzer II')],
    "Spermatids": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "Spermatocytes": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "Spermatogonia": [('single-end', 50,'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],   
    "spinalcord": [('single-end', 101, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer II'), ('single-end', 40, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "spleen": [('single-end', 36, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer II'), ('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000'), ('paired-end', 80, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "splenicB cells": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000'), ('single-end', 49, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 1500')],
    "striatal neurons": [('single-end', 100, 'RNA-Seq', 'other', 'Illumina HiSeq 2000')],
    "striated muscle": [('single-end', 86, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx')],
    "striatum": [('single-end', 38, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx'), ('single-end', 40, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx')],
    "substantia nigra": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000'), ('single-end', 53, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000'), ('single-end', 59, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "subventricularzone": [('single-end', 38, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx'), ('single-end', 40, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx'), ('paired-end', 85, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx'), ('paired-end', 100, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer IIx')],
    "tail fibroblast": [('single-end', 75, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "telencephalon": [('single-end', 36, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "TER119p erythroid cells": [('paired-end', 51, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "testicular": [('single-end', 100, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "thymus": [('single-end', 36, 'RNA-Seq', 'other',  'AB SOLiD System')],
    "trophoblast giant cells": [('single-end', 36, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer II')],
    "TSC": [('single-end', 36, 'RNA-Seq', 'cDNA', GAIIx)],
    "typeA spermatogonia": [('single-end', 100, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer II')],
    "typeB spermatogonia": [('single-end', 100, 'RNA-Seq', 'cDNA', 'Illumina Genome Analyzer II')],
    "upper molar": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "uterus": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "vas deferens": [('single-end', 50, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "ventral tagmental": [('single-end', 59, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000'), ('single-end', 53, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "white matter glia": [('single-end', 100, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "WholeBrainE14": [('single-end', 50, 'RNA-Seq', 'cDNA',  'AB SOLiD System')],
    "WholeBrainE18": [('single-end', 50, 'RNA-Seq', 'cDNA',  'AB SOLiD System')],
    "X2C embryo": [('paired-end', 90, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "X4C embryo": [('paired-end', 90, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "X8C embryo": [('paired-end', 90, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    "Zygote E1 C1": [('single-end', 53, 'RNA-Seq', 'cDNA', 'Illumina HiSeq 2000')],
    
    'adipocytes white': [('single-end', 36, 'RNA-seq', 'size fractionation', 'Illumina Genome Analyzer'),],
    'adrenal medulla': [('single-end', 36, 'RNA-seq', 'cDNA', 'Illumina Genome Analyzer II'),],
    'astrocyte': [('paired-end', 100, 'RNA-seq', '?', hiseq2000),],
    'BM macrophages': [('single-end', 00, 'RNA-seq', '?', hiseq1500),],
    'caecum': [('paired-end', 100, 'RNA-seq', '?', hiseq2000),],
    'carotid body': [('single-end', 36, 'RNA-seq', '?', GAII),],
    'CD4T cells': [('single-end', 49, 'RNA-seq', '?', hiseq1500),],
    'CD4T DPCD3hi': [('single-end', 36, 'RNA-seq', '?', GAII),],
    'CD4T DPCD3lo': [('single-end', 36, 'RNA-seq', '?', GAII),],
    'CD8T': [('single-end', 49, 'RNA-seq', '?', hiseq1500),],
    'CD8T nkg2dn': [('single-end', 51, 'RNA-seq', '?', hiseq2000),],
    'CD8T nkg2dp': [('single-end', 51, 'RNA-seq', '?', hiseq2000),],
    #'cerebral cortex endothelium': [('paired-end', 101, 'RNA-seq', '?', '?'),],
    'chondrocyte rib': [('single-end', 76, 'RNA-seq', '?', hiseq2000),],
    'CLP': [('single-end', 50, 'RNA-seq', '?', hiseq1500),],
    'CMP': [('single-end', 49, 'RNA-seq', '?', hiseq1500),],
    'colon epithelial cells': [('single-end', 51, 'RNA-seq', '?', hiseq2000),],
    #'cranial neural crest mandible': [('single-end', 100, 'RNA-seq', '?', '?'),], # Not used, MEFs?
    'DN1eP': [('single-end', 51, 'RNA-seq', '?', hiseq1000),],
    'DN1ePNKT': [('single-end', 51, 'RNA-seq', '?', hiseq1000),],
    'E105 lateral nasal prominence': [('single-end', 50, 'RNA-seq', '?', hiseq2500),],
    'E105 olfactory pit': [('single-end', 50, 'RNA-seq', '?', hiseq2500),],
    'E125 atrioventricular canal': [('paired-end', 75, 'RNA-seq', '?', MiSeq),],
    'E65 Epiblast AD': [('single-end', 51, 'RNA-seq', '?', hiseq2500),],
    'E65 Epiblast AP': [('single-end', 51, 'RNA-seq', '?', hiseq2500),],
    'E65 Epiblast PD': [('single-end', 51, 'RNA-seq', '?', hiseq2500),],
    'E65 Epiblast PP': [('single-end', 51, 'RNA-seq', '?', hiseq2500),],
    'E85 floor plate': [('single-end', 51, 'RNA-seq', '?', hiseq2500),],
    'E85 mesoderm': [('single-end', 50, 'RNA-seq', '?', hiseq2500),],
    'ectoplacental cone': [('single-end', 50, 'RNA-seq', '?', hiseq2000),],
    'erythrocytes typeA': [('single-end', 43, 'RNA-seq', '?', hiseq1500),],
    'erythrocytes typeB': [('single-end', 57, 'RNA-seq', '?', hiseq1500),],
    'ESC groundstate line1': [('paired-end', 100, 'RNA-seq', '?', hiseq2000),],
    'ESC naive 2iL': [('paired-end', 100, 'RNA-seq', '?', hiseq2000),], #NOT IN SRA
    'ESC naive 2iLGO': [('paired-end', 100, 'RNA-seq', '?', hiseq2000),],#NOT IN SRA
    'ESC PDL': [('paired-end', 100, 'RNA-seq', '?', hiseq2000),],#NOT IN SRA
    'GMP': [('single-end', 49, 'RNA-seq', '?', hiseq1500),],
    'hair follicle stem cells': [('single-end', 51, 'RNA-seq', '?', hiseq2000),],
    'hair follicle transit amplifying cells': [('single-end', 51, 'RNA-seq', '?', hiseq2000),],
    'HSC MPP1': [('paired-end', 100, 'RNA-seq', '?', hiseq2000),],#NOT IN SRA
    'HSC MPP2': [('paired-end', 100, 'RNA-seq', '?', hiseq2000),],#NOT IN SRA
    'HSC MPP3': [('paired-end', 100, 'RNA-seq', '?', hiseq2000),],#NOT IN SRA
    'HSC MPP4': [('paired-end', 100, 'RNA-seq', '?', hiseq2000),],#NOT IN SRA
    'iNKT': [('single-end', 100, 'RNA-seq', '?', hiseq2500),],
    'intestinal stem cell': [('paired-end', 51, 'RNA-seq', '?', GAII),],
    'intestinal subepithelial myofibroblasts adult': [('single-end', 50, 'RNA-seq', '?', hiseq2000),],
    'intestinal subepithelial myofibroblasts neonatal': [('single-end', 50, 'RNA-seq', '?', hiseq2000),],
    'large intestine': [('single-end', 50, 'RNA-seq', '?', 'AB SOLiD System'),],
    'LTHSC': [('single-end', 57, 'RNA-seq', '?', hiseq1500),],
    'mast cells cd25n': [('paired-end', 51, 'RNA-seq', '?', GAII),],
    'mast cells cd25p': [('paired-end', 51, 'RNA-seq', '?', GAII),],
    'mature sperm': [('single-end', 36, 'RNA-seq', '?', GAII),],
    'Medial ganglionic eminence neurons': [('single-end', 35, 'RNA-seq', '?', 'AB SOLiD System 3.0'),],
    'medullary thymic epithelial cell immature': [('single-end', 36, 'RNA-seq', '?', GAIIx),],
    'medullary thymic epithelial cell mature': [('single-end', 36, 'RNA-seq', '?', GAIIx),],
    'monocytes': [('single-end', 49, 'RNA-seq', '?', hiseq1500),],
    'MPP': [('single-end', 57, 'RNA-seq', '?', hiseq1500),],
    'MSC bone': [('paired-end', 100, 'RNA-seq', '?', hiseq2000),],
    'MSC skin': [('paired-end', 100, 'RNA-seq', '?', hiseq2000),],
    'MSC thymus': [('paired-end', 100, 'RNA-seq', '?', hiseq2000),],
    'neuron': [('paired-end', 101, 'RNA-seq', '?', hiseq2000),],
    'NK cells': [('single-end', 49, 'RNA-seq', '?', hiseq1500),],
    'NKT stage1': [('single-end', 50, 'RNA-seq', '?', hiseq1000),],
    'NKT stage2': [('single-end', 50, 'RNA-seq', '?', hiseq1000),],
    'NKT stage3': [('single-end', 50, 'RNA-seq', '?', hiseq1000),],
    'oligodendrocyte myelinating': [('paired-end', 101, 'RNA-seq', '?', hiseq2000),],
    'oligodendrocyte newly formed': [('paired-end', 101, 'RNA-seq', '?', hiseq2000),],
    'oligodendrocyte precursor': [('paired-end', 101, 'RNA-seq', '?', hiseq2000),],
    'pancreatic alpha': [('single-end', 51, 'RNA-seq', '?', hiseq2000),],
    'pancreatic beta': [('single-end', 51, 'RNA-seq', '?', hiseq2000),],
    'pgc female': [('paired-end', 100, 'RNA-seq', '?', hiseq2000),],
    'pgc male': [('paired-end', 100, 'RNA-seq', '?', hiseq2000),],
    'preadipocytes white': [('single-end', 36, 'RNA-seq', '?', GAII),],
    'prostate luminal cells': [('single-end', 101, 'RNA-seq', '?', hiseq2000),],
    'rsEpiSC': [('paired-end', 50, 'RNA-seq', '?', hiseq2500),],
    'skin': [('paired-end', 100, 'RNA-seq', '?', hiseq2000),],
    'small intestine cells': [('single-end', 51, 'RNA-seq', '?', hiseq1500),],
    'somatic gondal cell': [('paired-end', 100, 'RNA-seq', '?', hiseq2000),],
    'spermatids': [('single-end', 50, 'RNA-seq', '?', hiseq2000),],
    'spermatocytes': [('single-end', 50, 'RNA-seq', '?', hiseq2000),],
    'spermatogonia': [('single-end', 50, 'RNA-seq', '?', hiseq2000),],
    'SS Early blastocyst E4 C8': [('single-end', 51, 'RNA-seq', '?', hiseq2000),],
    'SS Early blastocyst E2 C16': [('single-end', 51, 'RNA-seq', '?', hiseq2000),],
    'SS Embryo2C early E1 C2': [('single-end', 51, 'RNA-seq', '?', hiseq2000),],
    'SS Embryo2C late E6 C2': [('single-end', 51, 'RNA-seq', '?', hiseq2000),],
    'SS Embryo2C mid E5 C2': [('single-end', 51, 'RNA-seq', '?', hiseq2000),],
    'SS Embryo4C E1 C2': [('single-end', 51, 'RNA-seq', '?', hiseq2000),],
    'SS Embryo8C E1 C1': [('single-end', 51, 'RNA-seq', '?', hiseq2000),],
    'SS Late blastocyst E2 C2': [('single-end', 51, 'RNA-seq', '?', hiseq2000),],
    'SS Late blastocyst E2 C8': [('single-end', 51, 'RNA-seq', '?', hiseq2000),],
    'SS Mid blastocyst E2 C17': [('single-end', 51, 'RNA-seq', '?', hiseq2000),],
    'SS Mid blastocyst E2 C9': [('single-end', 51, 'RNA-seq', '?', hiseq2000),],
    'SS Morula E1 C10': [('single-end', 51, 'RNA-seq', '?', hiseq2000),],
    'SS Zygote E1 C1': [('single-end', 51, 'RNA-seq', '?', hiseq2000),],
    'XEN': [('single-end', 50, 'RNA-seq', '?', hiseq2500),],
    'zona limitans intrathalamica': [('paired-end', 100, 'RNA-seq', '?', hiseq2000),],
    }
    
if __name__ == '__main__':
    from glbase import glload
    from .gene_layer_name import gene_layer_name

    # Check all sample names are actually used:
    expn = glload("../../pub/rsem-genes/genes_cpm_expression.glb")
 
    cond_names = expn.getConditionNames()
    
    print('\nFound in "rnaseq_library_parameters" but not in expn:')
    for c in sorted(rnaseq_library_parameters.keys()):
        if c not in cond_names:
            print('! %s' % (c,))
            
    print('\nFound in "expn" but not in rnaseq_library_parameters:')
    for c in cond_names:
        if c not in list(rnaseq_library_parameters.keys()):
            print("'%s': [('?', 00, 'RNA-seq', '?', '?'),]," % (c,))