

sample_description = {
    'adipocytes brown': 'Adipocytes (cultured, brown)',
    'adipocytes white': 'Adipocytes (cultured, white)',
    'adipose': 'Adipose',
    'adrenal medulla': 'Adrenal medulla',
    'astrocyte': 'Astrocyte',
    'B active': 'B cell (active)',
    'B cells CD19p': 'B cells CD19+',
    'B cells CD43m': 'B cells CD43-',
    'B germinal center': 'B cell (germinal center)',
    'B naive': 'B cell (naive)',
    'B resting': 'B cell (resting)',
    'basophilic erythroblast': 'Basophilic erythroblast',
    'blastocyst': 'Blastocyst',
    'BM macrophages': 'Bone marrow macrophages',
    'BM monocyte': 'Monocyte',
    'BM': 'Bone marrow',
    'BMDM cpg': 'BMDM +CpolyG',
    'BMDM IL1b': 'BMDM +IL-1b',
    'BMDM lipidA 0m': 'BMDM -lipidA',
    'BMDM lipidA 360m': 'BMDM +lipidA 360 mins',
    'BMDM MALP2': 'BMDM +MALP2',
    'BMDM pIFNg': 'BMDM +IFNg',
    'BMDM pIL4': 'BMDM +IL-4',
    'BMDM pINFa': 'BMDM +IFNa',
    'BMDM TGFb': 'BMDM +TGFb',
    'BMDM': 'BMDM',
    'brain': 'Brain',
    'caecum': 'Caecum (E13.5)',
    'carotid body': 'Carotid body',
    'CD4T cells': 'CD4+ T cells',
    'CD4T DPCD3hi': 'CD4T DP CD3hi',
    'CD4T DPCD3lo': 'CD4T DP CD3lo',
    'CD4T iTreg': 'CD4+ iTreg cells',
    'CD4T mIL21': 'CD4+ T cells -IL-21',
    'CD4T pIL21': 'CD4+ T cells +IL-21',
    'CD4T Th1': 'CD4+ Th1 cells',
    'CD4T Th17': 'CD4+ Th17 cells ',
    'CD4T Th2': 'CD4+ Th2 cells',
    'CD4T Th9': 'CD4+ Th9 cells',
    'CD4T Treg': 'CD4+ Treg cells',
    'CD8T il2': 'CD8+ T cells +IL-2',
    'CD8T nkg2dn': 'CD4+ T NKG2D- cells',
    'CD8T nkg2dp': 'CD4+ T NKG2D+ cells',
    'CD8T': 'CD8+ T cells',
    'cerebellar gran neurons': 'Cerebellar granular neurons',
    'cerebellum': 'Cerebellum',
    #'cerebral cortex endothelium': 'Cerebral cortex endothelium',
    'chondrocyte rib': 'Chondrocyte (Rib)',
    'CLP': 'Common lymphoid progenitor',
    'CMP': 'Common myeloid progenitor',
    'colon epithelial cells': 'Colon epithelial cells',
    'colon': 'Colon',
    'cortex neuron': 'Cortex neuron',
    'cortex': 'Cortex',
    'cortical thymic epithelial': 'Cortical thymic epithelial',
    #'cranial neural crest mandible': 'Cranial neural crest mandible',
    'DC CD11bp': 'DC CD11+',
    'DC CD8p': 'DC CD8+',
    'dendritic cells': 'Dendritic cells (BMDC)',
    'dentate gyrus': 'Dentate gyrus',
    'dermal fibroblast': 'Dermal fibroblast',
    'DN1': 'Double negative 1 (DN1) thymic cells',
    'DN1eP': 'DN1e',
    'DN1ePNKT': 'NKT (derived) ',
    'DN2a': 'Double negative 2a (DN2a) thymic cells',
    'DN2b': 'Double negative 2b (DN2b) thymic cells',
    'DN3': 'Double negative 3 (DN3) thymic cells',
    'dorsal rootganglia': 'Dorsal root ganglia',
    'DP': 'Double positive thymic cells',
    'E105 central neural epithelium': 'Central neural epithelium (E10.5)',
    'E105 dorsal control neural epithelium': 'Dorsal control neural epithelium (E10.5)',
    'E105 lateral nasal prominence': 'Lateral nasal prominence (E10.5)',
    'E105 lateral prominence neural epithelium': 'Lateral prominence neural epithelium (E10.5)',
    'E105 mandibular arch': 'Mandibular arch (E10.5)',
    'E105 maxillary arch': 'Maxillary arch (E10.5)',
    'E105 olfactory pit': 'Olfactory pit (E10.5)',
    'E125 atrioventricular canal': 'Atrioventricular canal (E12.5)',
    'E165 cortical neurons': 'Cortical neurons (E16.5)',
    'E165 skin': 'Skin (E16.5)',
    'E185 dermis': 'Dermis (E18.5)',
    'E185 epidermis': 'Epidermis (E18.5)',
    'E65 Epiblast AD': 'Epiblast (E6.5) anterior-dorsal',
    'E65 Epiblast AP': 'Epiblast (E6.5) anterior-proximal',
    'E65 Epiblast PD': 'Epiblast (E6.5) posterior-dorsal',
    'E65 Epiblast PP': 'Epiblast (E6.5) posterior-proximal',
    'E85 caudal brain neural epithelium': 'Caudal brain neural epithelium (E8.5)',
    'E85 floor plate': 'Floor plate (E8.5)',
    'E85 mesoderm': 'Mesoderm (E8.5)',
    'E85 non floor plate neural epithelium': 'Non-floor plate neural epithelium (E8.5)',
    'E95 cranial mesenchyme': 'Cranial mesenchyme (E9.5)',
    'E95 epidermal ectoderm': 'Epidermal ectoderm (E9.5)' ,
    'E95 mandibular arch': 'Mandibular arch (E9.5)',
    'E95 maxillary arch': 'Maxillary arch (E9.5)',
    'ectoplacental cone': 'Ectoplacental cone',
    'elongative spermatids': 'Spermatids (elongated)',
    'eos im lm': 'Eosinophils -IL-10 -LPS',
    'eos im lp': 'Eosinophils -IL-10 +LPS',
    'epidermis basal E14': 'Basal epidermis (E14.5)',
    'epidermis suprabasal E14': 'Suprabasal epidermis (E14.5)',
    'epididymis': 'Epididymis',
    'EpiSC': 'EpiSC',
    'erythroblast': 'Erythroblast',
    'erythrocytes typeA': 'Erythrocytes type A',
    'erythrocytes typeB': 'Erythrocytes type B',
    'erythroid progenitor': 'Erythroid progenitor',
    'ESC 2iL HVn': 'Naive ESC (Hex-)',
    'ESC 2iL HVp': 'Naive ESC (Hex+)',
    'ESC B6J': 'ESCs (B6J)',
    'ESC groundstate line1': 'ESCs (groundstate)',
    'ESC naive 2iL': 'Naive ESCs (2iL)',
    'ESC naive 2iLGO': 'Naive ESCs (2iLGO)',
    'ESC PDL': 'ESCs (PDL)',
    'ESC V65': 'ESCs (V6.5)',
    'ESC ZHBTc4': 'ESCs (ZHBTc4)',
    'ESC': 'ESCs (E14)',
    'eye': 'Eye',
    'fatpad': 'Fatpad',
    'frontal cortex': 'Frontal cortex',
    'GMP': 'Granulocyte-monocyte progenitor',
    'granulocytes': 'Granulocytes',
    'hair follicle stem cells': 'Hair follicle stem cells',
    'hair follicle transit amplifying cells': 'Hair follicle transit amplifying cells',
    'hair follicle': 'Hair follicle',
    'heart': 'Heart',
    'hippocampus neuron': 'Hippocampus neuron',
    'hippocampus tissue': 'Hippocampus tissue',
    'hippocampus': 'Hippocampus',
    'HSC MPP1': 'Hematopoietic stem cells (MPP1)',
    'HSC MPP2': 'Hematopoietic stem cells (MPP2)',
    'HSC MPP3': 'Hematopoietic stem cells (MPP3)',
    'HSC MPP4': 'Hematopoietic stem cells (MPP4)',
    'HSC': 'Hematopoietic stem cells',
    'ICM E35': 'Inner cell mass (E3.5)',
    'ICM E375': 'Inner cell mass (E3.75)',
    'ILC2': 'Innate lymphoid cell (Type 2)',
    'ileum': 'Ileum',
    'iNKT': 'Invariant NKT',
    'intestinal stem cell': 'Intestinal stem cell',
    'intestinal subepithelial myofibroblasts adult': 'Intestinal subepithelial myofibroblasts (adult)',
    'intestinal subepithelial myofibroblasts neonatal': 'Intestinal subepithelial myofibroblasts (neonatal)',
    'intestine': 'Intestine',
    'keratinocytes': 'Keratinocyte',
    'kidney': 'Kidney',
    'large intestine': 'Large intestine',
    'liver': 'Liver',
    'lower molar': 'Lower molar',
    'LTHSC': 'Long-term HSC',
    'lung': 'Lung',
    'lungFibroblasts': 'Lung fibroblasts',
    'mac im lm': 'Macrophages -IL10 -LPS',
    'mac im lp': 'Macrophages -IL10 +LPS',
    'mac ip lm': 'Macrophages +IL10 -LPS',
    'mac ip lp': 'Macrophages +IL10 +LPS',
    'mammary tissue': 'Mammary tissue',
    'mast cells cd25n': 'Mast cells (CD25-)',
    'mast cells cd25p': 'Mast cells (CD25+)',
    'mature sperm': 'Mature sperm',
    'Medial ganglionic eminence neurons': 'Medial ganglionic eminence neurons',
    'medullary thymic epithelial cell immature': 'Medullary thymic epithelial cell (immature)',
    'medullary thymic epithelial cell mature': 'Medullary thymic epithelial cell (mature)',
    'medullary thymic epithelial': 'Medullary thymic epithelial',
    'MEF': 'MEF',
    'megakaryoblast': 'Megakaryoblast',
    'megakryocyte erythroid progenitor': 'Megakaryocyte erythroid progenitor',
    'microglia': 'Microglia',
    'monocytes': 'Monocytes',
    'morula': 'Morula',
    'motor neurons': 'Motor neurons',
    'MPP': 'Multipotent progenitor',
    'MSC bone': 'MSC (bone)',
    'MSC skin': 'MSC (skin)',
    'MSC thymus': 'MSC (thymus)',
    'mst im lm': 'Mast cell -IL10 -LPS',
    'mst im lp': 'Mast cell -IL10 +LPS',
    'mst ip lm': 'Mast cell +IL10 -LPS',
    'mst ip lp': 'Mast cell +IL10 +LPS',
    'myelocytes': 'Myelocytes',
    'myeloid': 'Myeloid cells',
    'myoblast': 'Myoblast',
    'naive cd4t 24h': 'Naive CD4+ T cells, anti-CD3/28 treated',
    'neocortex cortical plate': 'Neocortex cortical plate',
    'neocortex subventricular zone': 'Neocortex subventricular zone',
    'neocortex ventricular zone': 'Neocortex ventricular zone',
    'neonatal tail fibroblast': 'Neonatal tail fibroblast',
    'neu im lm': 'Neutrophil -IL10 -LPS',
    'neu im lp': 'Neutrophil -IL10 +LPS',
    'neu ip lm': 'Neutrophil +IL10 -LPS',
    'neu ip lp': 'Neutrophil +IL10 +LPS',
    'neuron': 'Neuron',
    'NK cells': 'Natural killer cells',
    'NKT stage1': 'NKT stage1',
    'NKT stage2': 'NKT stage2',
    'NKT stage3': 'NKT stage3',
    'NPC': 'Neural progenitor cell',
    'nucleus accumbens': 'Nucleus accumbens',
    'olfactory bulb': 'Olfactory bulb',
    'oligodendrocyte myelinating': 'Oligodendrocyte (myelinating)',
    'oligodendrocyte newly formed': 'Oligodendrocyte (newly formed)',
    'oligodendrocyte precursor': 'Oligodendrocyte (precursor)',
    'oocytes': 'Oocytes',
    'orthochromatic erythroblast': 'Orthochromatic erythroblast',
    'oviduct': 'Oviduct',
    'pancreatic alpha': 'Pancreatic cell (alpha)',
    'pancreatic beta': 'Pancreatic cell (beta)',
    'patski': 'Embryonic kidney fibroblast',
    'pgc female': 'PGC (female)',
    'pgc male': 'PGC (male)',
    'pineal gland': 'Pineal gland',
    'placenta': 'Placenta',
    'polychromatic erythroblast': 'Polychromatic erythroblast',
    'preadipocytes brown': 'pre-Adipocytes (brown)',
    'preadipocytes white': 'pre-Adipocytes (white)',
    'preB': 'pre-B cells',
    'primary adipocytes brown': 'Adipocytes (brown)',
    'primary adipocytes white': 'Adipocytes (white)',
    'proB fracB': 'pro-B (fraction B)',
    'proB fracCC': 'pro-B (fraction CC`)',
    'proB': 'pro-B cells',
    'proerythroblast': 'Proerythroblast',
    'promyelocytes': 'Promyelocytes',
    'pronuclei': 'Pronuclei',
    'prostate basal cells': 'Prostate basal cells',
    'prostate luminal cells': 'Prostate luminal cells',
    'retina': 'Retina',
    'round spermatids': 'Spermatids (round)',
    'rsEpiSC': 'EpiSC (region-selective)',
    'sdc im lm': 'splenic DC -IL10 -LPS',
    'sdc im lp': 'splenic DC -IL10 +LPS',
    'sdc ip lm': 'splenic DC +IL10 -LPS',
    'sdc ip lp': 'splenic DC +IL10 +LPS',
    'skeletal muscle': 'Skeletal muscle',
    'skin epithelial': 'Skin epithelial',
    #'skin': 'Skin',
    'small intestine cells': 'Small intestine cells',
    'somatic gondal cell': 'Somatic gonadal cell',
    'spermatids': 'Spermatids',
    'spermatocytes': 'Spermatocytes',
    'spermatogonia': 'Spermatogonia',
    'spinalcord': 'Spinal cord',
    'spleen': 'Spleen',
    'splenicB cells': 'splenic B cells',
    'SS Early blastocyst E2 C16': 'Blastocyst (Early) ICM',
    'SS Early blastocyst E4 C8': 'Blastocyst (Early) TE',
    'SS Embryo2C early E1 C2': '2C Embryo (early)', # The single cell embryo data.
    'SS Embryo2C late E6 C2': '2C Embryo (late)',
    'SS Embryo2C mid E5 C2': '2C Embryo (middle)',
    'SS Embryo4C E1 C2': '4C Embryo (single-cell)',
    'SS Embryo8C E1 C1': '8C Embryo (single-cell)',
    'SS Late blastocyst E2 C2': 'Blastocyst (Late) PrE', # I can't identify a good ICM sample, so rely on other data for ICM
    'SS Late blastocyst E2 C8': 'Blastocyst (Late) TE',
    'SS Mid blastocyst E2 C17': 'Blastocyst (Mid) TE',
    'SS Mid blastocyst E2 C9': 'Blastocyst (Mid) ICM',
    'SS Morula E1 C10': 'Morula (single-cell)',
    'SS Zygote E1 C1': 'Zygote',
    'striated muscle': 'Striated muscle',
    'striatum': 'Striatum',
    'substantia nigra': 'Substantia nigra',
    'subventricularzone': 'Subventricular zone',
    'tail fibroblast': 'Tail fibroblast',
    'telencephalon': 'Telencephalon',
    'TER119p erythroid cells': 'Erythroid cells (TER119+)',
    'testicular': 'Testicular cells',
    'thymus': 'Thymus',
    'trophoblast giant cells': 'Polyploid trophoblast giant cells (E9.5)',
    'TSC': 'Trophoblast stem cells',
    'upper molar': 'Upper molar',
    'uterus': 'Uterus',
    'vas deferens': 'Vas deferens',
    'ventral tagmental': 'Ventral tegmental',
    'white matter glia': 'White-matter glia',
    'X2clc': '2C-like cells (MERVL+ Zscan+)',
    'X2clc D1 rp3': '2C-like cells (MERVL+)',
    'X2C embryo': '2C Embryo',
    'X4C embryo': '4C Embryo',
    'X8C embryo': '8C Embryo',
    'XEN': 'XEN cells',
    'zona limitans intrathalamica': 'Zona limitans intrathalamica',
    }

if __name__ == '__main__':
    from glbase3 import glload
    from .gene_layer_name import gene_layer_name

    # Check all sample names are actually used:
    expn = glload("../../te_counts/genes_cpm_expression.glb")

    cond_names = expn.getConditionNames()

    print('\nFound in "sample_description" but not in expn:')
    for c in sorted(sample_description.keys()):
        if c not in cond_names:
            print('! %s' % (c,))

    print('\nFound in "expn" but not in sample_description:')
    for c in cond_names:
        if c not in list(sample_description.keys()):
            print("'%s': ," % (c,))
    print()
    print('Spell check')
    # For spell check:
    for s in sorted(sample_description.values()):
        print(s)
