
'''
This replace:
: \"([-+0-9A-Za-z \(\),\/.]*)\",
: (None, 100, None, None, ''),
'''

derivation_type = {
    "eos im lm": None,
    "eos im lp": None,
    "mac im lm": None,
    "mac im lp": None,
    "mac ip lm": None,
    "mac ip lp": None,
    "adipocytes": None,
    "adipocytes brown": None,
    "adipose": None,
    "BM": None,
    "BMDM": None,
    "BMDM cpg": None,
    "BMDM IL1b": None,
    "BMDM MALP2": None,
    "BMDM pIFNg": None,
    "BMDM pIL4": None,
    "BMDM pINFa": None,
    "BMDM TGFb": None,
    'DP': None,
    "DN1": None,
    "DN2a": None,
    "DN2b": None,
    "DN3": None,
    "CD4T Treg": None,
    "CD4T iTreg": None,
    "CD4T mIL21": None,
    "CD4T pIL21": None,
    "CD4T Th17": None,
    "CD4T Th1": None,
    "CD4T Th2": None,
    "CD4T Th9": None,
    "CD4Tcd328": None,
    "CD4Tuntre": None,
    "CD8T untre": None,
    "CD8T il2": None,
    "CD4T naive acd328": None,
    "cerebellum": None,
    "cortex": None,
    "dendritic cells": None,
    "E105 forelimb": None,
    "E105 hindlimb": None,
    "E16dermis": None,
    "E16epidermis": None,
    "E16skin": None,
    "ESC": None,
    "ESC V65": None,
    "ESC ZHBTc4": None,
    "heart": None,
    "intestine": None,
    "kidney": None,
    "liver": None,
    "lung": None,
    "lungFibroblasts": None,
    "MEF": None,
    "Neuron NCAMp": None,
    "NPC": None,
    "preadipocytes": None,
    "preadipocytes brown": None,
    "preB": None,
    "primary adipocytes brown": None,
    "primary adipocytes white": None,
    "proB": None,
    "spinalcord": None,
    "spleen": None,
    "TSC": None,
    "BcellCD43m": None,
    "BcellsCD19p": None,
    "cerebrum": None,
    "fatpad": None,
    "GenitalFatPad": None,
    "LgIntestine": None,
    "liver E1429bkgd": None,
    "liverE145": None,
    "naiveT": None,
    "thymus": None,
    "WholeBrainE14": None,
    "WholeBrainE18": None,
    "mst im lm": None,
    "mst im lp": None,
    "mst ip lm": None,
    "mst ip lp": None,
    "neu im lm": None,
    "neu im lp": None,
    "neu ip lm": None,
    "neu ip lp": None,
    "sdc im lm": None,
    "sdc im lp": None,
    "sdc ip lm": None,
    "sdc ip lp": None,  
    "DC CD11bp": None,
    "DC CD8p": None,
    "testicular": None,
    "BMDM lipidA 0m": None,
    "BMDM lipidA20m": None,
    "BMDM lipidA 30m": None,
    "BMDM lipidA 360m": None,
    "BMDM lipidA 60m": None,
    "E165 cortical neurons": None,
    "elongative spermatids": None,
    "erythroblast": None,
    "leptotene spermatocytes": None,
    "megakaryoblast": None,
    "megakryocyte erythroid progenitor": None,
    "pachytene spermatocytes": None,
    "pgc": None,
    "prim typeA spermatogonia": None,
    "proB fracB": None,
    "proB fracCC": "pro-B (fraction CC')",
    "round spermatids": None,
    "splenicB cells": None,
    "striatal neurons": None,
    "typeA spermatogonia": None,
    "typeB spermatogonia": None,
    "brain": None, 
    "cerebellar gran neurons": None,
    "colon": None,
    "dorsal rootganglia": None,
    "epidermis basal E14": None,
    "epidermis suprabasal E14": None,
    "ESC B6J": None,
    "eye": None,
    "hair follicle": None,
    "keratinocytes": None,
    "lower molar": None,
    "motor neurons": None,
    "myoblast": None,
    "neocortex cortical plate": None,
    'neocortex subventricular zone': None,
    'neocortex ventricular zone': None,
    'oocytes': None,
    'pineal gland': None,
    'placenta': None,
    'retina': None,
    'skeletal muscle': None,
    'sperm': None,
    'striated muscle': None,
    'substantia nigra': None,
    'telencephalon': None,
    'upper molar': None,
    'ventral tagmental': None,
    "blastocyst": None,
    "ICM E375": None,
    "ICM E35": None,
    "Epiblast": None,
    "trophoblast giant cells": None,
    "patski": None,
    "dentate gyrus": None,
    'B germinal center': None,
    'B resting': None,
    'Bactive': None,
    'Bnaive': None,
    "Caecum": None,
    'cardiac precursors': None,
    'cardiomyocytes': None,
    'cortical thymic epithelial': None,
    'medullary thymic epithelial': None,
    'dermal fibroblast': None,
    'epididymis': None,
    'EpiSC': None,
    'erythroid progenitor': None,
    'frontal cortex': None,
    'granulocytes': None,
    'Intestinal subepithelial myofibroblasts adult': None,
    'Intestinal subepithelial myofibroblasts neonatal': None,
    'mesodermal cells': None,
    'myelocytes': None,
    'promyelocytes': None,
    'neonatal tail fibroblast': None,
    'olfactory bulb': None,
    'oviduct': None,
    'uterus': None,
    'vas deferens': None,
    'X2C embryo': None,
    'X4C embryo': None,
    'X8C embryo': None,
    'prostate basal cells': None,
    'skin epithelial': None,
    'striatum': None,
    'subventricularzone': None,
    'tail fibroblast': None,
    'HSC': None,
    'myeloid': None,
    'nucleus accumbens': None,
    'morula': None,
    "Embryo2C early E1 C2": None, # The single cell embryo data.
    'Embryo2C late E6 C2': None,
    'Embryo2C mid E5 C2': None,
    'Early blastocyst E4 C8': None, 
    'Early blastocyst E2 C16': None,
    'Late blastocyst E2 C2': None, # I can't identify a good ICM sample, so rely on other data for ICM
    'Late blastocyst E2 C8': None,
    'Mid blastocyst E2 C17': None,
    'Mid blastocyst E2 C9': None,
    'Embryo4C E1 C2': None,
    'Embryo8C E1 C1': None,
    'Morula E1 C10': None,
    'basophilic erythroblast': None,
    'BM monocyte': None,
    'cortex neuron': None,
    'hippocampus neuron': None,
    'hippocampus': None,
    'hippocampus tissue': None,
    'ileum': None,
    'mammary tissue': None,
    'Matrue sperm': None,
    'microglia': None,
    'orthochromatic erythroblast': None,
    'polychromatic erythroblast': None,
    'proerythroblast': None,
    'pronuclei': None,
    'Spermatids': None,
    'Spermatocytes': None,
    'Spermatogonia': None,
    'white matter glia': None,
    'TER119p erythroid cells': None,
    'Zygote E1 C1': None,
    'E105 central neural epithelium': None,
    'E105 dorsal control neural epithelium': None,
    'E105 lateral prominence neural epithelium': None,
    'E105 mandibular arch': None,
    'E105 maxillary arch': None,
    'E105 medial nasal prominence': None,
    'E85 caudal brain neural epithelium': None,
    'E85 non floor plate neural epithelium': None,
    'E95 cranial mesenchyme': None,
    'E95 epidermal ectoderm': 'Epidermal ectoderm (E9.5)' ,
    'E95 mandibular arch': None,
    'E95 maxillary arch': None,
    'ILC2': None,
    'ESC 2iL HVn': None,
    'ESC 2iL HVp': None,
    }